1. Veri setini yükleme
2. MLP yapısını tanımlama
3. Model parametrelerini başlatma
4. İleri yayılım (forward propagation)
5. Maliyet (cost) hesaplama
6. Geri yayılım (Backpropagation)
7. Parametre güncelleme Update Propagation
8. Tüm adımların entegrasyonu

## Veri setini yükleme

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("drug_consumption_balanced.csv")

In [49]:
df['Cannabis'] = df['Cannabis'].apply(lambda x: 0 if x == 'CL0' else 1)

df = df.drop(columns= ['ID'])
cols = [c for c in df.columns if c != 'Cannabis'] + ['Cannabis']
df = df[cols]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826 entries, 0 to 825
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        826 non-null    float64
 1   Gender     826 non-null    float64
 2   Education  826 non-null    float64
 3   Country    826 non-null    float64
 4   Ethnicity  826 non-null    float64
 5   Nscore     826 non-null    float64
 6   Escore     826 non-null    float64
 7   Oscore     826 non-null    float64
 8   Ascore     826 non-null    float64
 9   Cscore     826 non-null    float64
 10  Impulsive  826 non-null    float64
 11  SS         826 non-null    float64
 12  Cannabis   826 non-null    int64
dtypes: float64(12), int64(1)
memory usage: 84.0 KB

In [51]:
df.head(50)

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
0,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.24649,0.47617,0.88309,-0.15487,1.81175,0.52975,0.40148,1
1,0.49788,0.48246,-0.05921,0.21128,-0.31685,0.04257,0.47617,-0.84732,-0.76096,1.13407,0.52975,0.76540,1
2,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,-0.34799,0.63779,1.88511,-0.60633,0.25953,0.19268,0.76540,1
3,0.49788,0.48246,1.98437,0.96082,-0.31685,0.52135,-0.30033,1.65653,0.28783,1.13407,-1.37983,-2.07848,1
4,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,0.16767,-0.97631,0.59042,0.93949,0.88113,0.40148,1
5,-0.07854,-0.48246,-0.05921,-0.57009,-0.31685,1.23461,-0.57545,0.88309,-0.01729,-0.89891,0.88113,0.76540,1
6,0.49788,0.48246,1.16365,0.96082,-0.31685,-0.58016,0.47617,-0.58331,-0.30172,0.93949,-0.21712,-0.84637,1
7,-0.07854,0.48246,1.98437,-0.57009,-0.31685,-1.05308,0.80523,-0.31776,-0.15487,0.93949,-0.21712,-0.52593,1
8,-0.07854,0.48246,-0.61113,-0.57009,-0.31685,-0.24649,-0.43999,-1.55521,0.13136,0.58489,-1.37983,-1.54858,1
9,-0.07854,0.48246,1.98437,0.96082,-0.31685,-1.05308,1.45421,-0.84732,0.94156,0.58489,-0.71126,-0.52593,1
10,-0.95197,0.48246,-1.43719,0.96082,-0.31685,-0.34799,0.47617,-0.17779,-0.60633,-0.14277,-0.71126,-0.84637,1
11,-0.95197,-0.48246,-1.22751,-0.57009,-0.31685,-0.05188,0.96248,-0.01928,0.43852,-0.65253,0.88113,1.22470,1
12,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.41667,1.11406,-1.11902,2.46262,1.30612,-1.37983,-1.54858,1
13,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.62967,-0.15487,1.88511,1.45039,0.12331,0.88113,-0.84637,1
14,-0.95197,0.48246,0.45468,0.96082,-0.31685,1.02119,-0.69509,0.88309,-1.77200,-0.40581,0.19268,0.40148,1
15,1.09449,0.48246,0.45468,0.96082,-0.31685,1.37297,-0.69509,0.29338,1.45039,0.12331,-1.37983,-0.52593,1
16,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,1.13281,-0.43999,0.29338,-0.76096,-0.14277,1.86203,-0.21575,1
17,0.49788,0.48246,1.16365,0.96082,-0.31685,0.62967,-0.15487,-1.97495,-0.15487,-1.01450,0.88113,0.40148,1
18,0.49788,-0.48246,1.98437,-0.28519,-0.31685,1.72012,-0.15487,0.88309,-1.07533,-0.40581,-0.21712,-0.21575,1
19,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-2.05048,0.16767,0.72330,0.13136,0.75830,0.19268,1.22470,1
20,1.09449,-0.48246,1.16365,0.96082,-0.50212,-0.92104,0.80523,-0.31776,0.94156,0.25953,-1.37983,-1.54858,1
21,-0.95197,-0.48246,-1.43719,-0.57009,-0.31685,0.73545,-1.23177,0.58331,-0.60633,-0.40581,0.52975,0.40148,1
22,-0.95197,0.48246,0.45468,0.96082,-0.31685,0.31287,0.16767,-1.55521,0.43852,1.13407,-1.37983,-1.18084,1
23,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.19430,1.74091,1.43533,0.76096,-0.00665,0.88113,1.22470,1
24,-0.07854,0.48246,1.16365,0.96082,-1.10702,-1.32828,0.47617,-0.01928,1.11406,0.12331,-1.37983,-1.54858,1
25,-0.07854,0.48246,1.16365,0.96082,-0.31685,-0.24649,0.80523,-0.58331,1.45039,0.93949,0.19268,-0.84637,1
26,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.58016,0.63779,-1.97495,0.28783,0.75830,-0.71126,-0.52593,1
27,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,2.12700,-0.94779,-0.45174,-0.30172,-1.64101,1.29221,0.07987,1
28,0.49788,-0.48246,0.45468,0.24923,-0.31685,-0.58016,-0.69509,-2.39883,-0.30172,-0.27607,-2.55524,-1.18084,1
29,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.69163,1.28610,1.24033,0.13136,1.13407,0.52975,1.92173,1
30,1.09449,-0.48246,0.45468,0.96082,-0.31685,0.22393,-1.09207,-0.71727,-0.30172,-0.65253,0.19268,-0.84637,1
31,-0.07854,-0.48246,-0.05921,0.96082,-0.31685,-0.05188,-0.94779,-1.68062,0.13136,0.75830,-0.21712,-0.84637,1
32,2.59171,0.48246,-1.73790,0.96082,-0.31685,-0.14882,-0.80615,-0.97631,0.76096,0.41594,-1.37983,-1.54858,1
33,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.14882,0.80523,-1.27553,-0.01729,2.04506,0.19268,-1.18084,1
34,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,1.23461,-1.23177,0.44585,-0.01729,0.25953,-1.37983,-1.54858,1
35,-0.07854,-0.48246,-0.61113,0.96082,-0.31685,0.62967,0.32197,-0.71727,-0.30172,-0.00665,-0.21712,-1.54858,1
36,1.09449,-0.48246,1.16365,0.96082,-0.31685,-0.92104,0.80523,-0.01928,-0.01729,0.41594,-1.37983,-1.54858,1
37,1.09449,0.48246,0.45468,-0.57009,-0.31685,1.23461,1.74091,0.88309,-1.92595,-1.64101,0.88113,1.22470,1
38,0.49788,-0.48246,-0.05921,0.96082,-1.10702,-0.92104,1.45421,-1.27553,-0.45321,-0.00665,-0.21712,0.07987,1
39,0.49788,-0.48246,-0.05921,-0.57009,-0.31685,1.60383,-1.76250,-0.01928,0.13136,-1.51840,0.88113,-0.52593,1
40,-0.07854,-0.48246,0.45468,0.96082,-0.31685,1.23461,-1.76250,-0.31776,0.13136,0.41594,-1.37983,-0.21575,1
41,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.13606,1.11406,-0.97631,0.43852,-0.27607,-0.71126,-0.52593,1
42,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.41667,0.63779,-0.31776,-0.91699,-0.00665,0.19268,0.76540,1
43,-0.07854,0.48246,0.45468,0.96082,-0.50212,-0.24649,2.12700,-2.21069,-0.91699,-0.14277,1.29221,-0.21575,1
44,-0.95197,-0.48246,0.45468,-0.57009,-0.31685,0.62967,1.45421,0.58331,0.13136,0.93949,0.19268,1.92173,1
45,1.09449,0.48246,-1.73790,0.96082,-0.31685,0.41667,-1.37639,-2.09015,0.59042,-0.27607,-1.37983,-2.07848,1
46,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,0.91093,-2.11437,-0.17779,-0.45321,-0.89891,-1.37983,-0.84637,1
47,1.09449,0.48246,0.45468,0.96082,-0.31685,-1.19430,1.58487,0.29338,0.76096,0.41594,-2.55524,-1.18084,1
48,-0.07854,-0.48246,1.16365,0.96082,-0.31685,-0.14882,0.32197,-1.27553,1.11406,1.81175,0.52975,1.22470,1
49,0.49788,0.48246,-0.05921,0.96082,-0.31685,-0.34799,0.80523,-1.68062,-0.60633,0.41594,-0.21712,-0.21575,1

In [52]:
df.describe()

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
count,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.0
mean,0.168080,0.085277,0.057608,0.508167,-0.328278,-0.060029,0.027327,-0.197196,0.110081,0.194614,-0.186178,-0.258899,1.0
std,0.909124,0.475151,0.984273,0.659379,0.173798,0.985466,0.978178,0.973696,0.969876,0.972190,0.938166,0.972517,0.0
min,-0.951970,-0.482460,-2.435910,-0.570090,-1.107020,-2.756960,-2.728270,-3.273930,-3.005370,-2.728270,-2.555240,-2.078480,1.0
25%,-0.951970,-0.482460,-0.611130,-0.285190,-0.316850,-0.763195,-0.575450,-0.847320,-0.606330,-0.405810,-0.711260,-0.846370,1.0
50%,-0.078540,0.482460,-0.059210,0.960820,-0.316850,-0.051880,0.003320,-0.177790,0.131360,0.259530,-0.217120,-0.215750,1.0
75%,1.094490,0.482460,0.454680,0.960820,-0.316850,0.629670,0.637790,0.445850,0.760960,0.939490,0.529750,0.401480,1.0
max,2.591710,0.482460,1.984370,0.960820,0.126000,3.273930,2.859500,2.449040,2.756960,3.464360,2.901610,1.921730,1.0

In [53]:
df.isnull().sum()

Age          0
Gender       0
Education    0
Country      0
Ethnicity    0
Nscore       0
Escore       0
Oscore       0
Ascore       0
Cscore       0
Impulsive    0
SS           0
Cannabis     0
dtype: int64

In [54]:
df = df.sample(frac = 1, random_state = 42).reset_index(drop= True)

In [55]:
df.head(50)

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
0,-0.07854,0.48246,1.16365,0.96082,-0.22166,0.31287,0.63779,-0.58331,0.13136,-0.14277,0.19268,-0.21575,1
1,-0.95197,-0.48246,-0.61113,-0.57009,0.12600,-0.46725,2.12700,1.88511,-0.60633,-1.25773,1.86203,1.92173,1
2,-0.95197,-0.48246,-0.61113,-0.28519,-0.31685,-1.32828,-0.30033,0.88309,1.11406,-1.01450,-0.71126,-0.21575,1
3,1.09449,0.48246,1.16365,0.96082,-0.31685,-1.05308,1.74091,0.58331,0.43852,2.04506,-0.21712,-0.52593,1
4,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.62967,0.63779,0.44585,0.13136,-2.57309,1.86203,1.22470,1
5,2.59171,-0.48246,0.45468,0.96082,-0.31685,-1.86962,-0.15487,-0.58331,2.46262,0.41594,-1.37983,-2.07848,1
6,-0.95197,-0.48246,-0.05921,0.96082,-0.31685,-0.92104,-0.30033,-0.71727,0.59042,0.41594,-0.71126,-1.54858,1
7,-0.95197,-0.48246,-1.43719,-0.09765,-0.31685,-0.34799,0.80523,0.72330,0.59042,-0.89891,1.86203,1.22470,1
8,1.09449,0.48246,0.45468,0.96082,-0.31685,0.62967,-0.57545,0.72330,-0.15487,0.41594,0.52975,-0.84637,1
9,1.09449,-0.48246,0.45468,0.96082,-0.31685,1.02119,-1.50796,-0.71727,0.28783,-0.89891,-0.21712,0.76540,1
10,1.09449,-0.48246,0.45468,0.96082,-0.31685,1.02119,-0.30033,-0.71727,-0.60633,-0.00665,-1.37983,-1.18084,1
11,-0.95197,-0.48246,-1.73790,-0.09765,-0.31685,0.82562,1.28610,0.29338,-1.21213,-0.89891,0.88113,1.92173,1
12,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,1
13,1.09449,-0.48246,0.45468,0.96082,-0.31685,0.22393,-1.09207,-0.71727,-0.30172,-0.65253,0.19268,-0.84637,1
14,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.31287,-0.57545,-0.31776,-1.47955,-0.89891,-1.37983,0.76540,1
15,-0.95197,0.48246,0.45468,0.96082,-0.31685,-0.58016,0.80523,0.44585,0.59042,1.30612,-0.71126,0.76540,1
16,0.49788,-0.48246,-0.05921,-0.57009,-0.31685,1.60383,-1.76250,-0.01928,0.13136,-1.51840,0.88113,-0.52593,1
17,-0.07854,0.48246,0.45468,-0.57009,0.11440,0.82562,-1.63340,-0.31776,-1.47955,-1.13788,-1.37983,-1.18084,1
18,1.09449,-0.48246,-1.43719,0.96082,-0.31685,0.91093,-0.15487,-0.17779,-0.15487,0.25953,0.88113,0.07987,1
19,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-0.24649,0.16767,-0.31776,-1.21213,0.75830,1.29221,0.40148,1
20,0.49788,0.48246,0.45468,0.96082,-0.31685,-0.67825,0.32197,-0.97631,0.59042,0.12331,-0.71126,-0.84637,1
21,0.49788,0.48246,-1.22751,0.21128,-0.31685,-0.24649,-0.57545,-0.58331,-0.15487,0.25953,-1.37983,-1.54858,1
22,-0.07854,-0.48246,0.45468,-0.09765,-0.31685,1.02119,0.16767,0.58331,0.43852,0.75830,-1.37983,0.76540,1
23,-0.95197,0.48246,0.45468,0.96082,-0.31685,-0.14882,0.96248,-1.55521,2.23427,1.63088,-0.21712,-0.52593,1
24,-0.07854,0.48246,-0.05921,0.96082,-0.31685,-0.67825,0.96248,-1.11902,-0.15487,0.58489,0.19268,-0.21575,1
25,-0.95197,0.48246,1.16365,0.96082,0.12600,0.62967,0.32197,-0.58331,0.13136,0.75830,-0.21712,-0.21575,1
26,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,1.37297,-0.30033,0.29338,-0.15487,-1.78169,0.19268,-0.21575,1
27,1.09449,0.48246,-0.61113,0.96082,-0.31685,0.04257,-0.30033,-2.21069,-0.15487,-0.14277,-0.71126,-0.84637,1
28,-0.07854,-0.48246,-0.05921,0.96082,-0.31685,2.12700,-1.37639,0.14143,-0.30172,-1.64101,1.29221,-0.21575,1
29,1.09449,0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,0.58331,0.13136,0.75830,-2.55524,-0.84637,1
30,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,0.22393,-1.23177,0.88309,-0.76096,-0.27607,-0.21712,0.76540,1
31,0.49788,0.48246,-0.05921,0.96082,-0.31685,-1.55078,1.45421,0.44585,0.43852,0.58489,-0.71126,-1.18084,1
32,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,1.49158,-1.37639,-2.63199,1.81866,-1.25773,0.52975,-1.18084,1
33,-0.95197,-0.48246,0.45468,-0.57009,-0.31685,0.41667,-1.92173,0.88309,-0.15487,-0.52745,0.19268,-0.52593,1
34,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-0.79151,1.11406,-0.01928,1.28610,2.04506,0.88113,0.40148,1
35,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.52135,-0.30033,-0.58331,-0.76096,-0.52745,-0.21712,0.76540,1
36,-0.07854,0.48246,-2.43591,-0.57009,-0.31685,-0.24649,0.63779,-0.71727,-0.91699,0.25953,1.29221,-0.21575,1
37,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.04257,1.28610,-0.01928,0.13136,0.75830,0.52975,0.76540,1
38,1.09449,0.48246,-0.05921,0.96082,-0.31685,-0.58016,0.32197,0.14143,-1.34289,0.93949,0.19268,-0.21575,1
39,2.59171,-0.48246,-0.05921,0.96082,-0.31685,-1.05308,-0.30033,0.29338,0.43852,0.75830,-0.21712,-0.52593,1
40,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.19430,1.74091,1.43533,0.76096,-0.00665,0.88113,1.22470,1
41,-0.07854,-0.48246,-0.61113,-0.28519,-0.31685,1.02119,-2.72827,0.14143,-0.01729,-0.14277,0.19268,0.07987,1
42,0.49788,-0.48246,0.45468,-0.28519,-0.31685,1.49158,-0.57545,0.88309,-1.62090,-0.40581,-0.21712,0.76540,1
43,2.59171,0.48246,-1.73790,0.24923,-0.31685,-0.14882,-0.15487,-1.42424,-1.34289,-0.00665,-0.21712,0.76540,1
44,1.09449,-0.48246,-0.05921,0.96082,-0.31685,0.13606,0.00332,-0.45174,-0.60633,0.75830,-0.21712,0.40148,1
45,-0.95197,-0.48246,-0.05921,0.96082,-0.31685,0.91093,-1.37639,-0.31776,-1.92595,-1.38502,0.88113,0.07987,1
46,-0.07854,0.48246,-1.73790,0.96082,-0.31685,-1.19430,-1.23177,-2.21069,1.81866,0.58489,-2.55524,-2.07848,1
47,0.49788,0.48246,1.16365,0.96082,-0.31685,-0.79151,0.32197,-0.01928,-0.15487,1.13407,-0.21712,-0.21575,1
48,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.14882,-0.30033,-0.84732,-0.30172,1.46191,-0.71126,-0.21575,1
49,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-0.05188,-2.32338,-0.84732,-1.77200,-0.40581,1.29221,-0.21575,1

In [56]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]

In [57]:
print("X type is " + str(type(X)))
print("X shape is " + str(X.shape))
print("y type is " + str(type(y)))
print("y shape is " + str(y.shape))

X type is <class 'pandas.core.frame.DataFrame'>
X shape is (826, 12)
y type is <class 'pandas.core.series.Series'>
y shape is (826,)

In [58]:
X = X.to_numpy()

In [59]:
y = y.to_numpy().reshape(-1, 1)

In [60]:
print("X type is " + str(type(X)))
print("X shape is " + str(X.shape))
print("y type is " + str(type(y)))
print("y shape is " + str(y.shape))

X type is <class 'numpy.ndarray'>
X shape is (826, 12)
y type is <class 'numpy.ndarray'>
y shape is (826, 1)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
train_df = pd.read_csv("drug_train.csv")
test_df = pd.read_csv("drug_test.csv")

X_train = train_df.drop(columns=['Cannabis']).to_numpy()
y_train = train_df['Cannabis'].to_numpy().reshape(-1, 1)

X_test = test_df.drop(columns=['Cannabis']).to_numpy()
y_test = test_df['Cannabis'].to_numpy().reshape(-1, 1)

In [63]:
import numpy as np

print("Train class distribution:")
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

print("Test class distribution:")
unique, counts = np.unique(y_test, return_counts=True)
print(dict(zip(unique, counts)))

Train class distribution:
{np.int64(0): np.int64(330), np.int64(1): np.int64(330)}
Test class distribution:
{np.int64(0): np.int64(83), np.int64(1): np.int64(83)}

In [64]:
print("X train shape is " + str(X_train.shape))
print("X test shape is " + str(X_test.shape))
print("y train shape is " + str(y_train.shape))
print("y test shape is " + str(y_test.shape))

X train shape is (660, 12)
X test shape is (166, 12)
y train shape is (660, 1)
y test shape is (166, 1)

## Model Mimarisi (Define Network Structure)

Input layer size is X.shape[1]
Hidden layer size is 5.
Output layer size is 1.

Örneğin; giriş katmanı boyutu X.shape[1], gizli katman nöron sayısı 5 ve çıkış katmanı 1 olabilir.

In [65]:
print("X.shape is " + str(X.shape))
print("X.shape[1] is " + str(X.shape[1]))

X.shape is (826, 12)
X.shape[1] is 12

## Modeli Başlatmak (Initialize Model Parameters)

In [66]:
def initialize_parameters(n_x, n_h, n_y = 1):
    np.random.seed(42)
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))

    parameters = {
        "W1" : W1,
        "b1" : b1,
        "W2" : W2,
        "b2" : b2
    }
    return parameters

In [67]:
test_parameters = initialize_parameters(X.shape[1], 5, 1)

In [68]:
print("W1 = " + str(test_parameters["W1"]))
print("b1 = " + str(test_parameters["b1"]))
print("W2 = " + str(test_parameters["W2"]))
print("b2 = " + str(test_parameters["b2"]))

W1 = [[ 0.00496714 -0.00138264  0.00647689  0.0152303  -0.00234153 -0.00234137
   0.01579213  0.00767435 -0.00469474  0.0054256  -0.00463418 -0.0046573 ]
 [ 0.00241962 -0.0191328  -0.01724918 -0.00562288 -0.01012831  0.00314247
  -0.00908024 -0.01412304  0.01465649 -0.00225776  0.00067528 -0.01424748]
 [-0.00544383  0.00110923 -0.01150994  0.00375698 -0.00600639 -0.00291694
  -0.00601707  0.01852278 -0.00013497 -0.01057711  0.00822545 -0.01220844]
 [ 0.00208864 -0.0195967  -0.01328186  0.00196861  0.00738467  0.00171368
  -0.00115648 -0.00301104 -0.01478522 -0.00719844 -0.00460639  0.01057122]
 [ 0.00343618 -0.0176304   0.00324084 -0.00385082 -0.00676922  0.00611676
   0.01031     0.0093128  -0.00839218 -0.00309212  0.00331263  0.00975545]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.00479174 -0.00185659 -0.01106335 -0.01196207  0.00812526]]
b2 = [[0.]]

In [69]:
print("W1 = " + str(test_parameters["W1"].shape))
print("b1 = " + str(test_parameters["b1"].shape))
print("W2 = " + str(test_parameters["W2"].shape))
print("b2 = " + str(test_parameters["b2"].shape))
print("X_train = " + str(X_train.shape))

W1 = (5, 12)
b1 = (5, 1)
W2 = (1, 5)
b2 = (1, 1)
X_train = (660, 12)

## Forward Propagation

In [70]:
def forward_propagation(X, parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    # gizli katman
    Z1 = np.dot(W1, X.T) + b1
    A1 = np.tanh(Z1)

    # çıkış katmanı
    Z2 = np.dot(W2, A1) + b2
    A2 = 1/ (1 + np.exp(-Z2))

    cache = {"Z1": Z1, "A1": A1, "Z2":Z2, "A2":A2}
    return A2, cache

In [71]:
def sigmoid(Z):
    return 1 / (1 + np.exp(-1 * Z))

In [72]:
test_A2, test_cache = forward_propagation(X_train, test_parameters)

In [73]:
print("A2 test:" + str(test_A2))
print("A2 test shape:" + str(test_A2.shape))

A2 test:[[0.4999994  0.4998063  0.50006475 0.50004023 0.49977039 0.49986767
  0.49978868 0.49990372 0.50006563 0.49973509 0.49999007 0.50003005
  0.5000181  0.50006597 0.49972793 0.50008532 0.50003179 0.49997648
  0.50009873 0.49994194 0.50005925 0.49994302 0.50006961 0.49980998
  0.50005478 0.4999435  0.50009845 0.49993997 0.50000087 0.49999897
  0.50013391 0.49995456 0.50010664 0.50012255 0.50000678 0.50011701
  0.50007812 0.49998519 0.50010599 0.50008712 0.50003405 0.50001519
  0.49996957 0.49994914 0.50013311 0.50004358 0.49999031 0.49997014
  0.50006223 0.49995231 0.50007382 0.49993929 0.50010635 0.5000238
  0.49998492 0.50013956 0.49984515 0.50008432 0.49989184 0.50008375
  0.50000799 0.49988905 0.50002982 0.50004425 0.49981808 0.49988721
  0.49997508 0.50015704 0.50006147 0.50003355 0.50015446 0.50004146
  0.50013044 0.49997655 0.5000226  0.50001012 0.49987755 0.50009493
  0.49999002 0.50004169 0.49996188 0.49980846 0.49997633 0.49992674
  0.49998315 0.50002319 0.49984301 0.50009504 0.50003723 0.50020503
  0.49990943 0.49984736 0.50009048 0.49996343 0.4998742  0.4999679
  0.50013893 0.50000741 0.50006666 0.49995768 0.49995639 0.49986298
  0.50008376 0.49989858 0.49999405 0.49997137 0.5000916  0.49985538
  0.49990369 0.5000388  0.5000187  0.49994917 0.50001074 0.50015158
  0.49994661 0.50000373 0.50006659 0.49992198 0.50017289 0.49991796
  0.50009513 0.50001239 0.5000208  0.49993004 0.5001802  0.49994717
  0.49985267 0.50001153 0.50005977 0.50011632 0.49992241 0.49994609
  0.49999661 0.49998738 0.4997966  0.50013574 0.49999671 0.50002528
  0.49988364 0.50016621 0.49987927 0.50006629 0.49993504 0.49999418
  0.5000262  0.50015216 0.49995247 0.4999605  0.50012213 0.50008749
  0.49995567 0.50009102 0.49998674 0.50002611 0.50005092 0.49988133
  0.49998611 0.50005272 0.49997238 0.49992292 0.49984569 0.50004923
  0.50012888 0.49988479 0.4998966  0.49989129 0.49996305 0.50008997
  0.49982654 0.49997996 0.4999522  0.50000386 0.50011323 0.50005657
  0.49987887 0.49979991 0.50022489 0.50012214 0.5001005  0.49991812
  0.49990161 0.49986577 0.50006679 0.50011213 0.49992794 0.49998899
  0.49998639 0.50006264 0.49997211 0.50015282 0.49976696 0.50007717
  0.50000558 0.49991685 0.4999592  0.50001078 0.50005814 0.49997773
  0.49995096 0.50000578 0.50006844 0.50009142 0.49998813 0.50003683
  0.50003271 0.49987822 0.50004443 0.49990803 0.49999431 0.50013041
  0.49982424 0.49999832 0.49989113 0.50006315 0.49993302 0.49989825
  0.50008999 0.49984128 0.50009746 0.50002596 0.50006885 0.50026556
  0.50007387 0.50007351 0.5000813  0.50017905 0.49982309 0.49993403
  0.49991511 0.50005112 0.49977918 0.5000467  0.49995503 0.49991325
  0.50017941 0.49992105 0.50017263 0.49988104 0.50017193 0.49997955
  0.49978237 0.49995095 0.49993112 0.49993051 0.49998647 0.50006419
  0.50003994 0.49994747 0.49998439 0.49988266 0.49974831 0.50002903
  0.49985955 0.49997262 0.49997988 0.50005472 0.49994993 0.49994749
  0.49987154 0.49997624 0.49999144 0.50002093 0.50004651 0.50012346
  0.50012968 0.50007944 0.50013907 0.49995794 0.50001926 0.49990829
  0.49995602 0.49998221 0.50003765 0.50000896 0.50001992 0.50003317
  0.49992845 0.49991572 0.49991023 0.49996686 0.50016678 0.49996961
  0.50005421 0.49989065 0.49990197 0.50014065 0.50008046 0.50010012
  0.49999197 0.49989954 0.50012407 0.50003506 0.49981678 0.49966582
  0.50009973 0.49995833 0.50007435 0.500067   0.50026903 0.49988072
  0.49988488 0.50004774 0.50014924 0.49996318 0.49998981 0.5000474
  0.49991646 0.50006323 0.4999861  0.50018422 0.50017837 0.50014865
  0.49987799 0.50009484 0.49990626 0.50004818 0.49999281 0.49997533
  0.50001755 0.49990888 0.49993465 0.49991517 0.50002292 0.49999034
  0.49991012 0.50013691 0.50005221 0.50010359 0.50002582 0.50005688
  0.50004429 0.50002518 0.50009644 0.50006419 0.49983611 0.49999163
  0.50004327 0.50005927 0.49999615 0.49991357 0.4999224  0.49991259
  0.5000692  0.49993503 0.49985325 0.5000743  0.49991243 0.49998699
  0.50002817 0.49993165 0.49980825 0.49998628 0.49984435 0.49987503
  0.49984123 0.49986443 0.49999735 0.49996736 0.49999096 0.50022385
  0.50021353 0.50008237 0.50012026 0.49995558 0.50010431 0.50011277
  0.49989995 0.49997018 0.49979759 0.49996021 0.49991205 0.49995485
  0.49998541 0.50009694 0.49984425 0.50007321 0.49991338 0.49999318
  0.5000639  0.50015767 0.50000253 0.49984727 0.50005994 0.50014993
  0.49998515 0.50004871 0.50006229 0.50004791 0.50000253 0.49997945
  0.50013523 0.49991363 0.50004803 0.50007818 0.50008534 0.50015407
  0.49986888 0.50006415 0.50013817 0.49997737 0.50009662 0.50000564
  0.49986462 0.49984654 0.50008144 0.50004264 0.49992809 0.49994446
  0.50005044 0.50010987 0.50006887 0.50000393 0.49992303 0.49998677
  0.50011797 0.49998807 0.50008137 0.50022903 0.49998376 0.49996319
  0.50008376 0.49986571 0.50014909 0.50010908 0.50003048 0.49997947
  0.49994068 0.50010335 0.50009799 0.49990849 0.49984521 0.49983908
  0.5000621  0.49985276 0.49990891 0.49994303 0.49984891 0.50006402
  0.49992648 0.50011901 0.50008244 0.4997232  0.5002111  0.50009954
  0.49995469 0.50010357 0.49996272 0.50009664 0.49998948 0.49990389
  0.50013061 0.5000152  0.50008706 0.50002114 0.50002538 0.49989315
  0.50007407 0.50009438 0.5000504  0.5001117  0.50010648 0.49997342
  0.4999798  0.49996693 0.50011544 0.49990572 0.50002632 0.50008896
  0.50017391 0.49993648 0.49997685 0.50003652 0.49996008 0.49978902
  0.49997827 0.4999474  0.49998988 0.50009798 0.4998439  0.49985789
  0.49995919 0.50007665 0.50012965 0.50018869 0.49980201 0.50007006
  0.50010981 0.49988382 0.50001237 0.4998523  0.5000122  0.50011901
  0.49999498 0.49996279 0.50008918 0.49994848 0.49986267 0.49999931
  0.4999392  0.50017441 0.50015121 0.49981695 0.49995846 0.50014845
  0.49972417 0.49984086 0.50014726 0.49997809 0.49981795 0.50009778
  0.49997108 0.50006121 0.49980794 0.49980025 0.50002761 0.49995235
  0.4999216  0.49987916 0.49998292 0.50003974 0.49992861 0.50019882
  0.49999553 0.49988262 0.49985242 0.49997979 0.50004586 0.50000063
  0.50017679 0.49994692 0.5000207  0.49985492 0.50000525 0.50001399
  0.49983976 0.50008004 0.49992329 0.50009315 0.49998413 0.50003711
  0.50019673 0.50021838 0.49996861 0.50002949 0.50000329 0.49999384
  0.50015871 0.50014941 0.5002215  0.49997008 0.50018655 0.50017816
  0.49998677 0.49999844 0.50001783 0.50002422 0.50009324 0.49995568
  0.49984755 0.50009945 0.49993548 0.50024611 0.49980366 0.49987666
  0.49992872 0.50014069 0.50019373 0.49988648 0.49996046 0.50018644
  0.49976774 0.50006925 0.50001241 0.50001683 0.499885   0.50011764
  0.49982524 0.49990424 0.49992379 0.50006267 0.50012114 0.49980886
  0.49991586 0.50000558 0.50010404 0.49997464 0.5000307  0.49992374
  0.49984722 0.50002748 0.49998114 0.4998536  0.49997539 0.49991671
  0.50000218 0.49989103 0.49995222 0.50003372 0.4999812  0.49988588
  0.49981997 0.49983344 0.50004917 0.49997213 0.50012007 0.50001559
  0.49987222 0.49995574 0.50003747 0.49994356 0.49992406 0.4999337
  0.49991646 0.49988994 0.49995023 0.50002389 0.50004583 0.49996365
  0.50002026 0.49999408 0.50001654 0.50009768 0.50022449 0.5000188
  0.50016983 0.49987762 0.50001053 0.49995128 0.5000382  0.50001779
  0.50007818 0.50017728 0.49999458 0.49973644 0.49993171 0.49990819
  0.50005907 0.50003357 0.50004162 0.49996493 0.49987699 0.49988903
  0.4999081  0.49985674 0.50011097 0.49992594 0.50018872 0.50005845
  0.49992295 0.49995668 0.49998639 0.50010783 0.50007432 0.50007103
  0.49998038 0.50007933 0.50013488 0.49983392 0.49991394 0.50005235]]
A2 test shape:(1, 660)

In [74]:
print("Z1 is:" + str(test_cache["Z1"]))
print("A1 is:" + str(test_cache["A1"]))
print("Z2 is:" + str(test_cache["Z2"]))
print("A2 is:" + str(test_cache["A2"]))

Z1 is:[[ 0.00647269 -0.0380391   0.02773644 ...  0.03057421 -0.00943798
   0.00230527]
 [ 0.03166208  0.06593302  0.01329956 ... -0.04510584  0.02984269
  -0.00797343]
 [-0.00439729  0.02695114 -0.03486895 ...  0.02394851 -0.00904847
  -0.00028134]
 [ 0.00260895  0.04612559 -0.02743478 ...  0.05543067  0.02163915
  -0.0297551 ]
 [ 0.00860622  0.00180842 -0.03658719 ...  0.04011146 -0.02158648
  -0.018871  ]]
A1 is:[[ 0.0064726  -0.03802076  0.02772933 ...  0.03056469 -0.0094377
   0.00230527]
 [ 0.0316515   0.06583764  0.01329877 ... -0.04507527  0.02983383
  -0.00797326]
 [-0.00439727  0.02694462 -0.03485482 ...  0.02394393 -0.00904822
  -0.00028134]
 [ 0.00260895  0.04609291 -0.0274279  ...  0.05537397  0.02163578
  -0.02974632]
 [ 0.00860601  0.00180841 -0.03657088 ...  0.04008996 -0.02158313
  -0.01886876]]
Z2 is:[[-2.41275527e-06 -7.74818110e-04  2.58995418e-04  1.60935683e-04
  -9.18422468e-04 -5.29323371e-04 -8.45283464e-04 -3.85119331e-04
   2.62533692e-04 -1.05965301e-03 -3.97318736e-05  1.20211991e-04
   7.23863968e-05  2.63888442e-04 -1.08828959e-03  3.41295202e-04
   1.27178460e-04 -9.40918089e-05  3.94909486e-04 -2.32242332e-04
   2.36985322e-04 -2.27920026e-04  2.78455679e-04 -7.60061209e-04
   2.19132109e-04 -2.25998112e-04  3.93791834e-04 -2.40128869e-04
   3.47480181e-06 -4.12531550e-06  5.35646912e-04 -1.81768058e-04
   4.26566350e-04  4.90215408e-04  2.71286914e-05  4.68045217e-04
   3.12466267e-04 -5.92314139e-05  4.23965315e-04  3.48462165e-04
   1.36213912e-04  6.07792519e-05 -1.21725712e-04 -2.03439187e-04
   5.32455376e-04  1.74316531e-04 -3.87435272e-05 -1.19451063e-04
   2.48910181e-04 -1.90742551e-04  2.95269021e-04 -2.42830405e-04
   4.25400540e-04  9.51927770e-05 -6.03283467e-05  5.58222631e-04
  -6.19381486e-04  3.37279809e-04 -4.32654410e-04  3.34988611e-04
   3.19793482e-05 -4.43802055e-04  1.19288582e-04  1.77017100e-04
  -7.27697619e-04 -4.51162884e-04 -9.96918964e-05  6.28140849e-04
   2.45885918e-04  1.34186090e-04  6.17823536e-04  1.65837891e-04
   5.21759243e-04 -9.37801705e-05  9.04054019e-05  4.04697586e-05
  -4.89807860e-04  3.79715607e-04 -3.99368574e-05  1.66742687e-04
  -1.52486695e-04 -7.66158222e-04 -9.46662632e-05 -2.93022587e-04
  -6.74003049e-05  9.27703141e-05 -6.27962238e-04  3.80160868e-04
   1.48906016e-04  8.20129743e-04 -3.62287324e-04 -6.10571822e-04
   3.61916639e-04 -1.46284739e-04 -5.03194884e-04 -1.28383946e-04
   5.55736948e-04  2.96570805e-05  2.66653006e-04 -1.69265860e-04
  -1.74435385e-04 -5.48069690e-04  3.35057127e-04 -4.05669472e-04
  -2.37949196e-05 -1.14532450e-04  3.66416070e-04 -5.78489354e-04
  -3.85246931e-04  1.55183824e-04  7.48091378e-05 -2.03334310e-04
   4.29575719e-05  6.06322157e-04 -2.13547879e-04  1.49092531e-05
   2.66341032e-04 -3.12062210e-04  6.91565999e-04 -3.28171845e-04
   3.80512417e-04  4.95689567e-05  8.32025351e-05 -2.79847014e-04
   7.20794720e-04 -2.11331597e-04 -5.89316606e-04  4.61144732e-05
   2.39083805e-04  4.65279712e-04 -3.10358578e-04 -2.15650288e-04
  -1.35554325e-05 -5.04773806e-05 -8.13584000e-04  5.42958971e-04
  -1.31481738e-05  1.01118837e-04 -4.65423519e-04  6.64856320e-04
  -4.82900809e-04  2.65168052e-04 -2.59845185e-04 -2.32770959e-05
   1.04783131e-04  6.08644923e-04 -1.90127864e-04 -1.58018773e-04
   4.88539067e-04  3.49963292e-04 -1.77318135e-04  3.64090062e-04
  -5.30478222e-05  1.04458798e-04  2.03666875e-04 -4.74661864e-04
  -5.55572477e-05  2.10881381e-04 -1.10498576e-04 -3.08321711e-04
  -6.17258771e-04  1.96930798e-04  5.15519863e-04 -4.60845556e-04
  -4.13617681e-04 -4.34836784e-04 -1.47781115e-04  3.59884028e-04
  -6.93828040e-04 -8.01645202e-05 -1.91211678e-04  1.54409289e-05
   4.52921820e-04  2.26280354e-04 -4.84521612e-04 -8.00378526e-04
   8.99561387e-04  4.88562641e-04  4.01996230e-04 -3.27516132e-04
  -3.93578188e-04 -5.36918774e-04  2.67162326e-04  4.48518466e-04
  -2.88247953e-04 -4.40462532e-05 -5.44405395e-05  2.50558117e-04
  -1.11544845e-04  6.11278030e-04 -9.32173929e-04  3.08680406e-04
   2.23377040e-05 -3.32595772e-04 -1.63212899e-04  4.31203526e-05
   2.32558628e-04 -8.90976765e-05 -1.96173468e-04  2.31069600e-05
   2.73749954e-04  3.65699496e-04 -4.74926423e-05  1.47320493e-04
   1.30833677e-04 -4.87135303e-04  1.77733218e-04 -3.67883862e-04
  -2.27578049e-05  5.21627160e-04 -7.03024793e-04 -6.70015899e-06
  -4.35474898e-04  2.52609922e-04 -2.67929991e-04 -4.06992727e-04
   3.59951124e-04 -6.34876728e-04  3.89859603e-04  1.03823195e-04
   2.75385968e-04  1.06225750e-03  2.95475163e-04  2.94044315e-04
   3.25203851e-04  7.16182510e-04 -7.07659211e-04 -2.63880082e-04
  -3.39554941e-04  2.04483806e-04 -8.83287715e-04  1.86797101e-04
  -1.79886335e-04 -3.46997067e-04  7.17633212e-04 -3.15819108e-04
   6.90502770e-04 -4.75824171e-04  6.87722677e-04 -8.18094960e-05
  -8.70523764e-04 -1.96188964e-04 -2.75520678e-04 -2.77954830e-04
  -5.41275547e-05  2.56767121e-04  1.59761259e-04 -2.10139460e-04
  -6.24478720e-05 -4.69345391e-04 -1.00677172e-03  1.16110493e-04
  -5.61787198e-04 -1.09524455e-04 -8.04612498e-05  2.18896707e-04
  -2.00277801e-04 -2.10039938e-04 -5.13821840e-04 -9.50311688e-05
  -3.42270004e-05  8.37091980e-05  1.86024137e-04  4.93825202e-04
   5.18734858e-04  3.17779557e-04  5.56284957e-04 -1.68235176e-04
   7.70362902e-05 -3.66836318e-04 -1.75919201e-04 -7.11537404e-05
   1.50618561e-04  3.58345146e-05  7.96940793e-05  1.32675327e-04
  -2.86186673e-04 -3.37125519e-04 -3.59072131e-04 -1.32567863e-04
   6.67110388e-04 -1.21575455e-04  2.16850377e-04 -4.37404311e-04
  -3.92126623e-04  5.62592866e-04  3.21840769e-04  4.00477649e-04
  -3.21092097e-05 -4.01845173e-04  4.96268625e-04  1.40241025e-04
  -7.32868911e-04 -1.33670930e-03  3.98929692e-04 -1.66667690e-04
   2.97415935e-04  2.67986279e-04  1.07611929e-03 -4.77127987e-04
  -4.60495108e-04  1.90962680e-04  5.96963655e-04 -1.47287043e-04
  -4.07530535e-05  1.89589090e-04 -3.34172026e-04  2.52907439e-04
  -5.55948792e-05  7.36889769e-04  7.13466500e-04  5.94591645e-04
  -4.88051574e-04  3.79359523e-04 -3.74965850e-04  1.92721649e-04
  -2.87482590e-05 -9.86842904e-05  7.02157087e-05 -3.64471721e-04
  -2.61411623e-04 -3.39337651e-04  9.16930753e-05 -3.86429717e-05
  -3.59521071e-04  5.47628109e-04  2.08846076e-04  4.14368730e-04
   1.03291699e-04  2.27502226e-04  1.77175863e-04  1.00704608e-04
   3.85748939e-04  2.56750796e-04 -6.55552491e-04 -3.34671338e-05
   1.73084312e-04  2.37073685e-04 -1.53803732e-05 -3.45723783e-04
  -3.10399452e-04 -3.49626627e-04  2.76788260e-04 -2.59882188e-04
  -5.86988697e-04  2.97184407e-04 -3.50276603e-04 -5.20563857e-05
   1.12674083e-04 -2.73407017e-04 -7.66990835e-04 -5.48628881e-05
  -6.22613548e-04 -4.99866262e-04 -6.35081681e-04 -5.42297233e-04
  -1.05967231e-05 -1.30565000e-04 -3.61508434e-05  8.95404052e-04
   8.54132604e-04  3.29497742e-04  4.81042793e-04 -1.77690208e-04
   4.17255821e-04  4.51065803e-04 -4.00218056e-04 -1.19269336e-04
  -8.09642995e-04 -1.59150813e-04 -3.51798900e-04 -1.80582885e-04
  -5.83456910e-05  3.87764329e-04 -6.23003433e-04  2.92846876e-04
  -3.46499418e-04 -2.72687747e-05  2.55615137e-04  6.30670061e-04
   1.01288162e-05 -6.10921948e-04  2.39760162e-04  5.99712366e-04
  -5.94074073e-05  1.94844735e-04  2.49140859e-04  1.91653333e-04
   1.01295994e-05 -8.22103442e-05  5.40921714e-04 -3.45498470e-04
   1.92113141e-04  3.12737811e-04  3.41376817e-04  6.16287089e-04
  -5.24485966e-04  2.56593882e-04  5.52689253e-04 -9.05222025e-05
   3.86486196e-04  2.25613255e-05 -5.41508591e-04 -6.13859160e-04
   3.25767171e-04  1.70548330e-04 -2.87646813e-04 -2.22142414e-04
   2.01769356e-04  4.39496599e-04  2.75480944e-04  1.57186338e-05
  -3.07893924e-04 -5.29085860e-05  4.71883921e-04 -4.77020424e-05
   3.25496755e-04  9.16125324e-04 -6.49494582e-05 -1.47232797e-04
   3.35051420e-04 -5.37175486e-04  5.96366763e-04  4.36334538e-04
   1.21904225e-04 -8.21141888e-05 -2.37273764e-04  4.13414690e-04
   3.91944780e-04 -3.66045391e-04 -6.19175779e-04 -6.43662066e-04
   2.48403815e-04 -5.88959204e-04 -3.64374120e-04 -2.27893388e-04
  -6.04378722e-04  2.56069150e-04 -2.94085218e-04  4.76022496e-04
   3.29747166e-04 -1.10720769e-03  8.44397188e-04  3.98148544e-04
  -1.81222531e-04  4.14287960e-04 -1.49107353e-04  3.86551339e-04
  -4.20841859e-05 -3.84439340e-04  5.22456083e-04  6.07997608e-05
   3.48227027e-04  8.45538795e-05  1.01519286e-04 -4.27417508e-04
   2.96269908e-04  3.77508362e-04  2.01598194e-04  4.46793078e-04
   4.25930166e-04 -1.06300463e-04 -8.07852488e-05 -1.32271788e-04
   4.61764855e-04 -3.77125955e-04  1.05267109e-04  3.55833979e-04
   6.95620377e-04 -2.54085332e-04 -9.26095882e-05  1.46079235e-04
  -1.59672334e-04 -8.43905516e-04 -8.69015527e-05 -2.10392321e-04
  -4.04679449e-05  3.91929906e-04 -6.24391291e-04 -5.68439847e-04
  -1.63223167e-04  3.06597461e-04  5.18594062e-04  7.54774855e-04
  -7.91951772e-04  2.80233016e-04  4.39224058e-04 -4.64706470e-04
   4.94766180e-05 -5.90797255e-04  4.87949040e-05  4.76048943e-04
  -2.00936155e-05 -1.48839025e-04  3.56709147e-04 -2.06078478e-04
  -5.49336199e-04 -2.77563342e-06 -2.43207561e-04  6.97653705e-04
   6.04832733e-04 -7.32200366e-04 -1.66157122e-04  5.93817216e-04
  -1.10331932e-03 -6.36547428e-04  5.89046664e-04 -8.76228740e-05
  -7.28196885e-04  3.91131366e-04 -1.15696203e-04  2.44833648e-04
  -7.68228623e-04 -7.98983333e-04  1.10441496e-04 -1.90580766e-04
  -3.13589732e-04 -4.83341820e-04 -6.83220877e-05  1.58962478e-04
  -2.85542821e-04  7.95273527e-04 -1.78681867e-05 -4.69519078e-04
  -5.90319824e-04 -8.08563998e-05  1.83458730e-04  2.52378061e-06
   7.07162462e-04 -2.12324504e-04  8.28005923e-05 -5.80339485e-04
   2.10151218e-05  5.59778063e-05 -6.40950402e-04  3.20149029e-04
  -3.06850501e-04  3.72603254e-04 -6.34752154e-05  1.48440461e-04
   7.86919236e-04  8.73531284e-04 -1.25544271e-04  1.17960076e-04
   1.31482349e-05 -2.46295357e-05  6.34826666e-04  5.97623050e-04
   8.85980872e-04 -1.19694825e-04  7.46194822e-04  7.12649108e-04
  -5.29384424e-05 -6.22363395e-06  7.13313519e-05  9.68946900e-05
   3.72977204e-04 -1.77287294e-04 -6.09792958e-04  3.97788203e-04
  -2.58082824e-04  9.84424200e-04 -7.85367401e-04 -4.93372934e-04
  -2.85136979e-04  5.62742978e-04  7.74935384e-04 -4.54072251e-04
  -1.58144219e-04  7.45747204e-04 -9.29042066e-04  2.77005399e-04
   4.96510174e-05  6.73339028e-05 -4.59992950e-04  4.70576008e-04
  -6.99038648e-04 -3.83042900e-04 -3.04824871e-04  2.50664659e-04
   4.84572856e-04 -7.64559955e-04 -3.36572235e-04  2.23349481e-05
   4.16168235e-04 -1.01449332e-04  1.22796192e-04 -3.05053684e-04
  -6.11115271e-04  1.09937758e-04 -7.54579025e-05 -5.85586407e-04
  -9.84358283e-05 -3.33151277e-04  8.71539419e-06 -4.35871123e-04
  -1.91111108e-04  1.34865090e-04 -7.51954603e-05 -4.56479846e-04
  -7.20125185e-04 -6.66258466e-04  1.96678263e-04 -1.11474887e-04
   4.80261070e-04  6.23712974e-05 -5.11111198e-04 -1.77034611e-04
   1.49872440e-04 -2.25747728e-04 -3.03774211e-04 -2.65196706e-04
  -3.34153379e-04 -4.40228045e-04 -1.99069130e-04  9.55771654e-05
   1.83306670e-04 -1.45382177e-04  8.10319160e-05 -2.36607541e-05
   6.61578867e-05  3.90722951e-04  8.97964471e-04  7.51856264e-05
   6.79328850e-04 -4.89507186e-04  4.21251446e-05 -1.94892806e-04
   1.52787466e-04  7.11499082e-05  3.12737095e-04  7.09124661e-04
  -2.16723964e-05 -1.05422062e-03 -2.73148199e-04 -3.67224053e-04
   2.36286900e-04  1.34260725e-04  1.66480686e-04 -1.40275118e-04
  -4.92023623e-04 -4.43893277e-04 -3.67585068e-04 -5.73054322e-04
   4.43892037e-04 -2.96232614e-04  7.54865480e-04  2.33812962e-04
  -3.08200742e-04 -1.73278003e-04 -5.44287053e-05  4.31313867e-04
   2.97264867e-04  2.84124386e-04 -7.84797013e-05  3.17319001e-04
   5.39524256e-04 -6.64317749e-04 -3.44239616e-04  2.09383320e-04]]
A2 is:[[0.4999994  0.4998063  0.50006475 0.50004023 0.49977039 0.49986767
  0.49978868 0.49990372 0.50006563 0.49973509 0.49999007 0.50003005
  0.5000181  0.50006597 0.49972793 0.50008532 0.50003179 0.49997648
  0.50009873 0.49994194 0.50005925 0.49994302 0.50006961 0.49980998
  0.50005478 0.4999435  0.50009845 0.49993997 0.50000087 0.49999897
  0.50013391 0.49995456 0.50010664 0.50012255 0.50000678 0.50011701
  0.50007812 0.49998519 0.50010599 0.50008712 0.50003405 0.50001519
  0.49996957 0.49994914 0.50013311 0.50004358 0.49999031 0.49997014
  0.50006223 0.49995231 0.50007382 0.49993929 0.50010635 0.5000238
  0.49998492 0.50013956 0.49984515 0.50008432 0.49989184 0.50008375
  0.50000799 0.49988905 0.50002982 0.50004425 0.49981808 0.49988721
  0.49997508 0.50015704 0.50006147 0.50003355 0.50015446 0.50004146
  0.50013044 0.49997655 0.5000226  0.50001012 0.49987755 0.50009493
  0.49999002 0.50004169 0.49996188 0.49980846 0.49997633 0.49992674
  0.49998315 0.50002319 0.49984301 0.50009504 0.50003723 0.50020503
  0.49990943 0.49984736 0.50009048 0.49996343 0.4998742  0.4999679
  0.50013893 0.50000741 0.50006666 0.49995768 0.49995639 0.49986298
  0.50008376 0.49989858 0.49999405 0.49997137 0.5000916  0.49985538
  0.49990369 0.5000388  0.5000187  0.49994917 0.50001074 0.50015158
  0.49994661 0.50000373 0.50006659 0.49992198 0.50017289 0.49991796
  0.50009513 0.50001239 0.5000208  0.49993004 0.5001802  0.49994717
  0.49985267 0.50001153 0.50005977 0.50011632 0.49992241 0.49994609
  0.49999661 0.49998738 0.4997966  0.50013574 0.49999671 0.50002528
  0.49988364 0.50016621 0.49987927 0.50006629 0.49993504 0.49999418
  0.5000262  0.50015216 0.49995247 0.4999605  0.50012213 0.50008749
  0.49995567 0.50009102 0.49998674 0.50002611 0.50005092 0.49988133
  0.49998611 0.50005272 0.49997238 0.49992292 0.49984569 0.50004923
  0.50012888 0.49988479 0.4998966  0.49989129 0.49996305 0.50008997
  0.49982654 0.49997996 0.4999522  0.50000386 0.50011323 0.50005657
  0.49987887 0.49979991 0.50022489 0.50012214 0.5001005  0.49991812
  0.49990161 0.49986577 0.50006679 0.50011213 0.49992794 0.49998899
  0.49998639 0.50006264 0.49997211 0.50015282 0.49976696 0.50007717
  0.50000558 0.49991685 0.4999592  0.50001078 0.50005814 0.49997773
  0.49995096 0.50000578 0.50006844 0.50009142 0.49998813 0.50003683
  0.50003271 0.49987822 0.50004443 0.49990803 0.49999431 0.50013041
  0.49982424 0.49999832 0.49989113 0.50006315 0.49993302 0.49989825
  0.50008999 0.49984128 0.50009746 0.50002596 0.50006885 0.50026556
  0.50007387 0.50007351 0.5000813  0.50017905 0.49982309 0.49993403
  0.49991511 0.50005112 0.49977918 0.5000467  0.49995503 0.49991325
  0.50017941 0.49992105 0.50017263 0.49988104 0.50017193 0.49997955
  0.49978237 0.49995095 0.49993112 0.49993051 0.49998647 0.50006419
  0.50003994 0.49994747 0.49998439 0.49988266 0.49974831 0.50002903
  0.49985955 0.49997262 0.49997988 0.50005472 0.49994993 0.49994749
  0.49987154 0.49997624 0.49999144 0.50002093 0.50004651 0.50012346
  0.50012968 0.50007944 0.50013907 0.49995794 0.50001926 0.49990829
  0.49995602 0.49998221 0.50003765 0.50000896 0.50001992 0.50003317
  0.49992845 0.49991572 0.49991023 0.49996686 0.50016678 0.49996961
  0.50005421 0.49989065 0.49990197 0.50014065 0.50008046 0.50010012
  0.49999197 0.49989954 0.50012407 0.50003506 0.49981678 0.49966582
  0.50009973 0.49995833 0.50007435 0.500067   0.50026903 0.49988072
  0.49988488 0.50004774 0.50014924 0.49996318 0.49998981 0.5000474
  0.49991646 0.50006323 0.4999861  0.50018422 0.50017837 0.50014865
  0.49987799 0.50009484 0.49990626 0.50004818 0.49999281 0.49997533
  0.50001755 0.49990888 0.49993465 0.49991517 0.50002292 0.49999034
  0.49991012 0.50013691 0.50005221 0.50010359 0.50002582 0.50005688
  0.50004429 0.50002518 0.50009644 0.50006419 0.49983611 0.49999163
  0.50004327 0.50005927 0.49999615 0.49991357 0.4999224  0.49991259
  0.5000692  0.49993503 0.49985325 0.5000743  0.49991243 0.49998699
  0.50002817 0.49993165 0.49980825 0.49998628 0.49984435 0.49987503
  0.49984123 0.49986443 0.49999735 0.49996736 0.49999096 0.50022385
  0.50021353 0.50008237 0.50012026 0.49995558 0.50010431 0.50011277
  0.49989995 0.49997018 0.49979759 0.49996021 0.49991205 0.49995485
  0.49998541 0.50009694 0.49984425 0.50007321 0.49991338 0.49999318
  0.5000639  0.50015767 0.50000253 0.49984727 0.50005994 0.50014993
  0.49998515 0.50004871 0.50006229 0.50004791 0.50000253 0.49997945
  0.50013523 0.49991363 0.50004803 0.50007818 0.50008534 0.50015407
  0.49986888 0.50006415 0.50013817 0.49997737 0.50009662 0.50000564
  0.49986462 0.49984654 0.50008144 0.50004264 0.49992809 0.49994446
  0.50005044 0.50010987 0.50006887 0.50000393 0.49992303 0.49998677
  0.50011797 0.49998807 0.50008137 0.50022903 0.49998376 0.49996319
  0.50008376 0.49986571 0.50014909 0.50010908 0.50003048 0.49997947
  0.49994068 0.50010335 0.50009799 0.49990849 0.49984521 0.49983908
  0.5000621  0.49985276 0.49990891 0.49994303 0.49984891 0.50006402
  0.49992648 0.50011901 0.50008244 0.4997232  0.5002111  0.50009954
  0.49995469 0.50010357 0.49996272 0.50009664 0.49998948 0.49990389
  0.50013061 0.5000152  0.50008706 0.50002114 0.50002538 0.49989315
  0.50007407 0.50009438 0.5000504  0.5001117  0.50010648 0.49997342
  0.4999798  0.49996693 0.50011544 0.49990572 0.50002632 0.50008896
  0.50017391 0.49993648 0.49997685 0.50003652 0.49996008 0.49978902
  0.49997827 0.4999474  0.49998988 0.50009798 0.4998439  0.49985789
  0.49995919 0.50007665 0.50012965 0.50018869 0.49980201 0.50007006
  0.50010981 0.49988382 0.50001237 0.4998523  0.5000122  0.50011901
  0.49999498 0.49996279 0.50008918 0.49994848 0.49986267 0.49999931
  0.4999392  0.50017441 0.50015121 0.49981695 0.49995846 0.50014845
  0.49972417 0.49984086 0.50014726 0.49997809 0.49981795 0.50009778
  0.49997108 0.50006121 0.49980794 0.49980025 0.50002761 0.49995235
  0.4999216  0.49987916 0.49998292 0.50003974 0.49992861 0.50019882
  0.49999553 0.49988262 0.49985242 0.49997979 0.50004586 0.50000063
  0.50017679 0.49994692 0.5000207  0.49985492 0.50000525 0.50001399
  0.49983976 0.50008004 0.49992329 0.50009315 0.49998413 0.50003711
  0.50019673 0.50021838 0.49996861 0.50002949 0.50000329 0.49999384
  0.50015871 0.50014941 0.5002215  0.49997008 0.50018655 0.50017816
  0.49998677 0.49999844 0.50001783 0.50002422 0.50009324 0.49995568
  0.49984755 0.50009945 0.49993548 0.50024611 0.49980366 0.49987666
  0.49992872 0.50014069 0.50019373 0.49988648 0.49996046 0.50018644
  0.49976774 0.50006925 0.50001241 0.50001683 0.499885   0.50011764
  0.49982524 0.49990424 0.49992379 0.50006267 0.50012114 0.49980886
  0.49991586 0.50000558 0.50010404 0.49997464 0.5000307  0.49992374
  0.49984722 0.50002748 0.49998114 0.4998536  0.49997539 0.49991671
  0.50000218 0.49989103 0.49995222 0.50003372 0.4999812  0.49988588
  0.49981997 0.49983344 0.50004917 0.49997213 0.50012007 0.50001559
  0.49987222 0.49995574 0.50003747 0.49994356 0.49992406 0.4999337
  0.49991646 0.49988994 0.49995023 0.50002389 0.50004583 0.49996365
  0.50002026 0.49999408 0.50001654 0.50009768 0.50022449 0.5000188
  0.50016983 0.49987762 0.50001053 0.49995128 0.5000382  0.50001779
  0.50007818 0.50017728 0.49999458 0.49973644 0.49993171 0.49990819
  0.50005907 0.50003357 0.50004162 0.49996493 0.49987699 0.49988903
  0.4999081  0.49985674 0.50011097 0.49992594 0.50018872 0.50005845
  0.49992295 0.49995668 0.49998639 0.50010783 0.50007432 0.50007103
  0.49998038 0.50007933 0.50013488 0.49983392 0.49991394 0.50005235]]

## Compute Cost

In [75]:
print("Y shape is " +str(y_train.shape))

Y shape is (660, 1)

In [76]:
def compute_cost(A2, Y):
    m = A2.shape[1]
    cost = - (np.dot(np.log(A2), Y) + np.dot(np.log(1 - A2), (1 - Y))) / m
    cost = float(np.squeeze(cost))
    return cost

In [77]:
test_cost = compute_cost(test_A2, y_train)

In [78]:
print("test_cost is " + str(test_cost))
print("test_cost type is " + str(type(test_cost)))

test_cost is 0.693171374234361
test_cost type is <class 'float'>

## Backpropagation

In [79]:
print("A1 shape" + str(test_cache["A1"].shape))
print("A2 Shape" + str(test_A2.shape))
print("A2 Shape" + str(test_cache["A2"].shape))
print("W1 shape" + str(test_parameters["W1"].shape))
print("W2 shape" + str(test_parameters["W2"].shape))
print("y train shape" + str(y_train.shape))
print("X_train shape " + str(X_train.shape))

A1 shape(5, 660)
A2 Shape(1, 660)
A2 Shape(1, 660)
W1 shape(5, 12)
W2 shape(1, 5)
y train shape(660, 1)
X_train shape (660, 12)

In [80]:
def backpropagation(X, Y, cache, parameters):
    m = X.shape[0]

    W2 = parameters["W2"]
    A1 = cache["A1"]
    A2 = cache["A2"]

    # çıkış katmanı gradyanları
    dZ2 = A2 - Y.T
    dW2 = np.dot(dZ2, A1.T) / m
    db2 = np.sum(dZ2, axis = 1, keepdims = True) / m

    # gizli katman gradyanları
    dZ1 = np.dot(W2.T, dZ2) * (1-A1**2)
    dW1 = np.dot(dZ1, X) / m
    db1 = np.sum(dZ1, axis=1, keepdims = True) / m

    grads = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2}
    return grads

In [81]:
test_grads = backpropagation(X_train, y_train, test_cache, test_parameters)

In [82]:
print("dW1 shape is" + str(test_grads["dW1"].shape))
print("dW2 shape is" + str(test_grads["dW2"].shape))
print("db1 shape is" + str(test_grads["db1"].shape))
print("db2 shape is" + str(test_grads["db2"].shape))
print("b1 shape is" + str(test_parameters["b1"].shape))

dW1 shape is(5, 12)
dW2 shape is(1, 5)
db1 shape is(5, 1)
db2 shape is(1, 1)
b1 shape is(5, 1)

In [83]:
def update_parameters(parameters, grads, learning_rate = 0.01):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    paramaters = {
        "W1" : W1,
        "b1" : b1,
        "W2" : W2,
        "b2" : b2
    }

    return parameters

In [84]:
test_learned_parameters = update_parameters(test_parameters, test_grads)

In [85]:
test_learned_parameters["b2"].shape

(1, 1)

In [86]:
def nn_model(X, Y, n_x, n_h, n_y, n_steps = 100, print_cost = True):
    parameters = initialize_parameters(n_x, n_h, n_y)

    for i in range(0, n_steps):
        A2, cache = forward_propagation(X, parameters)
        cost = compute_cost(A2, Y)
        grads = backpropagation(X, Y, cache, parameters)
        parameters = update_parameters(parameters, grads)

        if print_cost and i % 10 == 0:
            print("cost %i %f" %(i,cost))

    return parameters

In [87]:
X_train.shape

(660, 12)

In [88]:
parameters = nn_model(X_train, y_train, X_train.shape[1], n_h=3, n_y=1, n_steps=500)

cost 0 0.693162
cost 10 0.693149
cost 20 0.693137
cost 30 0.693124
cost 40 0.693111
cost 50 0.693098
cost 60 0.693085
cost 70 0.693072
cost 80 0.693058
cost 90 0.693043
cost 100 0.693028
cost 110 0.693012
cost 120 0.692995
cost 130 0.692978
cost 140 0.692959
cost 150 0.692939
cost 160 0.692919
cost 170 0.692896
cost 180 0.692873
cost 190 0.692847
cost 200 0.692820
cost 210 0.692791
cost 220 0.692760
cost 230 0.692726
cost 240 0.692690
cost 250 0.692652
cost 260 0.692610
cost 270 0.692566
cost 280 0.692518
cost 290 0.692466
cost 300 0.692411
cost 310 0.692351
cost 320 0.692286
cost 330 0.692217
cost 340 0.692142
cost 350 0.692062
cost 360 0.691975
cost 370 0.691882
cost 380 0.691782
cost 390 0.691674
cost 400 0.691558
cost 410 0.691433
cost 420 0.691298
cost 430 0.691154
cost 440 0.690999
cost 450 0.690832
cost 460 0.690652
cost 470 0.690460
cost 480 0.690253
cost 490 0.690032

In [89]:
def predict(parameters, X):
    A2, cache = forward_propagation(X, parameters)
    predicts = A2 > 0.5
    return predicts

In [90]:
predicts = predict(parameters, X_test)

In [91]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
y_true = y_test.flatten()
y_pred = predicts.flatten()
acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='binary')
recall = recall_score(y_true, y_pred, average='binary')
f1 = f1_score(y_true, y_pred, average='binary')
conf_matrix = confusion_matrix(y_true, y_pred)
print(f"Accuracy: {acc:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_report(y_true, y_pred))

Accuracy: 0.8193
Precision: 0.8841
Recall: 0.7349
F1 Score: 0.8026

Confusion Matrix:
[[75  8]
 [22 61]]

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.90      0.83        83
           1       0.88      0.73      0.80        83

    accuracy                           0.82       166
   macro avg       0.83      0.82      0.82       166
weighted avg       0.83      0.82      0.82       166

In [92]:
parameters_n_h = [i for i in range(3, 11)]
parameters_n_steps = [i for i in range(100, 1100, 100)]
for n_h in parameters_n_h:
    for n_step  in parameters_n_steps:
        parameters = nn_model(X_train, y_train, X_train.shape[1], n_h = n_h, n_y = 1, n_steps = n_step, print_cost = False)
        predicts = predict(parameters, X_test)
        acc = accuracy_score(y_test.flatten(), predicts.flatten())
        print(f"n_h: {n_h}, n_step: {n_step}, acc: {acc}")

n_h: 3, n_step: 100, acc: 0.6746987951807228
n_h: 3, n_step: 200, acc: 0.7590361445783133
n_h: 3, n_step: 300, acc: 0.7771084337349398
n_h: 3, n_step: 400, acc: 0.8072289156626506
n_h: 3, n_step: 500, acc: 0.8192771084337349
n_h: 3, n_step: 600, acc: 0.8012048192771084
n_h: 3, n_step: 700, acc: 0.8012048192771084
n_h: 3, n_step: 800, acc: 0.8012048192771084
n_h: 3, n_step: 900, acc: 0.8012048192771084
n_h: 3, n_step: 1000, acc: 0.8072289156626506
n_h: 4, n_step: 100, acc: 0.7289156626506024
n_h: 4, n_step: 200, acc: 0.7831325301204819
n_h: 4, n_step: 300, acc: 0.8072289156626506
n_h: 4, n_step: 400, acc: 0.7951807228915663
n_h: 4, n_step: 500, acc: 0.7891566265060241
n_h: 4, n_step: 600, acc: 0.7951807228915663
n_h: 4, n_step: 700, acc: 0.8012048192771084
n_h: 4, n_step: 800, acc: 0.8012048192771084
n_h: 4, n_step: 900, acc: 0.8012048192771084
n_h: 4, n_step: 1000, acc: 0.8012048192771084
n_h: 5, n_step: 100, acc: 0.7289156626506024
n_h: 5, n_step: 200, acc: 0.7710843373493976
n_h: 5, n_step: 300, acc: 0.7891566265060241
n_h: 5, n_step: 400, acc: 0.8012048192771084
n_h: 5, n_step: 500, acc: 0.8132530120481928
n_h: 5, n_step: 600, acc: 0.8012048192771084
n_h: 5, n_step: 700, acc: 0.8012048192771084
n_h: 5, n_step: 800, acc: 0.8012048192771084
n_h: 5, n_step: 900, acc: 0.8012048192771084
n_h: 5, n_step: 1000, acc: 0.8012048192771084
n_h: 6, n_step: 100, acc: 0.7048192771084337
n_h: 6, n_step: 200, acc: 0.7891566265060241
n_h: 6, n_step: 300, acc: 0.7891566265060241
n_h: 6, n_step: 400, acc: 0.8012048192771084
n_h: 6, n_step: 500, acc: 0.8012048192771084
n_h: 6, n_step: 600, acc: 0.8012048192771084
n_h: 6, n_step: 700, acc: 0.7951807228915663
n_h: 6, n_step: 800, acc: 0.7951807228915663
n_h: 6, n_step: 900, acc: 0.7951807228915663
n_h: 6, n_step: 1000, acc: 0.8072289156626506
n_h: 7, n_step: 100, acc: 0.7831325301204819
n_h: 7, n_step: 200, acc: 0.7771084337349398
n_h: 7, n_step: 300, acc: 0.7831325301204819
n_h: 7, n_step: 400, acc: 0.7891566265060241
n_h: 7, n_step: 500, acc: 0.7891566265060241
n_h: 7, n_step: 600, acc: 0.7951807228915663
n_h: 7, n_step: 700, acc: 0.7951807228915663
n_h: 7, n_step: 800, acc: 0.7951807228915663
n_h: 7, n_step: 900, acc: 0.8012048192771084
n_h: 7, n_step: 1000, acc: 0.8192771084337349
n_h: 8, n_step: 100, acc: 0.7409638554216867
n_h: 8, n_step: 200, acc: 0.7831325301204819
n_h: 8, n_step: 300, acc: 0.7831325301204819
n_h: 8, n_step: 400, acc: 0.7891566265060241
n_h: 8, n_step: 500, acc: 0.7831325301204819
n_h: 8, n_step: 600, acc: 0.7831325301204819
n_h: 8, n_step: 700, acc: 0.7891566265060241
n_h: 8, n_step: 800, acc: 0.7951807228915663
n_h: 8, n_step: 900, acc: 0.7951807228915663
n_h: 8, n_step: 1000, acc: 0.8012048192771084
n_h: 9, n_step: 100, acc: 0.7530120481927711
n_h: 9, n_step: 200, acc: 0.7650602409638554
n_h: 9, n_step: 300, acc: 0.7831325301204819
n_h: 9, n_step: 400, acc: 0.7891566265060241
n_h: 9, n_step: 500, acc: 0.7891566265060241
n_h: 9, n_step: 600, acc: 0.7951807228915663
n_h: 9, n_step: 700, acc: 0.7951807228915663
n_h: 9, n_step: 800, acc: 0.8012048192771084
n_h: 9, n_step: 900, acc: 0.8192771084337349
n_h: 9, n_step: 1000, acc: 0.8192771084337349
n_h: 10, n_step: 100, acc: 0.7650602409638554
n_h: 10, n_step: 200, acc: 0.7771084337349398
n_h: 10, n_step: 300, acc: 0.7891566265060241
n_h: 10, n_step: 400, acc: 0.7951807228915663
n_h: 10, n_step: 500, acc: 0.7951807228915663
n_h: 10, n_step: 600, acc: 0.7951807228915663
n_h: 10, n_step: 700, acc: 0.8012048192771084
n_h: 10, n_step: 800, acc: 0.8072289156626506
n_h: 10, n_step: 900, acc: 0.8132530120481928
n_h: 10, n_step: 1000, acc: 0.8192771084337349