1. Veri setini yükleme
2. MLP yapısını tanımlama
3. Model parametrelerini başlatma
4. İleri yayılım (forward propagation)
5. Maliyet (cost) hesaplama
6. Geri yayılım (Backpropagation)
7. Parametre güncelleme Update Propagation
8. Tüm adımların entegrasyonu

## Veri setini yükleme

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("drug_consumption_balanced.csv")

In [49]:
df['Cannabis'] = df['Cannabis'].apply(lambda x: 0 if x == 'CL0' else 1)

df = df.drop(columns= ['ID'])
cols = [c for c in df.columns if c != 'Cannabis'] + ['Cannabis']
df = df[cols]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826 entries, 0 to 825
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        826 non-null    float64
 1   Gender     826 non-null    float64
 2   Education  826 non-null    float64
 3   Country    826 non-null    float64
 4   Ethnicity  826 non-null    float64
 5   Nscore     826 non-null    float64
 6   Escore     826 non-null    float64
 7   Oscore     826 non-null    float64
 8   Ascore     826 non-null    float64
 9   Cscore     826 non-null    float64
 10  Impulsive  826 non-null    float64
 11  SS         826 non-null    float64
 12  Cannabis   826 non-null    int64
dtypes: float64(12), int64(1)
memory usage: 84.0 KB

In [51]:
df.head(50)

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
0,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.24649,0.47617,0.88309,-0.15487,1.81175,0.52975,0.40148,1
1,0.49788,0.48246,-0.05921,0.21128,-0.31685,0.04257,0.47617,-0.84732,-0.76096,1.13407,0.52975,0.76540,1
2,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,-0.34799,0.63779,1.88511,-0.60633,0.25953,0.19268,0.76540,1
3,0.49788,0.48246,1.98437,0.96082,-0.31685,0.52135,-0.30033,1.65653,0.28783,1.13407,-1.37983,-2.07848,1
4,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,0.16767,-0.97631,0.59042,0.93949,0.88113,0.40148,1
5,-0.07854,-0.48246,-0.05921,-0.57009,-0.31685,1.23461,-0.57545,0.88309,-0.01729,-0.89891,0.88113,0.76540,1
6,0.49788,0.48246,1.16365,0.96082,-0.31685,-0.58016,0.47617,-0.58331,-0.30172,0.93949,-0.21712,-0.84637,1
7,-0.07854,0.48246,1.98437,-0.57009,-0.31685,-1.05308,0.80523,-0.31776,-0.15487,0.93949,-0.21712,-0.52593,1
8,-0.07854,0.48246,-0.61113,-0.57009,-0.31685,-0.24649,-0.43999,-1.55521,0.13136,0.58489,-1.37983,-1.54858,1
9,-0.07854,0.48246,1.98437,0.96082,-0.31685,-1.05308,1.45421,-0.84732,0.94156,0.58489,-0.71126,-0.52593,1
10,-0.95197,0.48246,-1.43719,0.96082,-0.31685,-0.34799,0.47617,-0.17779,-0.60633,-0.14277,-0.71126,-0.84637,1
11,-0.95197,-0.48246,-1.22751,-0.57009,-0.31685,-0.05188,0.96248,-0.01928,0.43852,-0.65253,0.88113,1.22470,1
12,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.41667,1.11406,-1.11902,2.46262,1.30612,-1.37983,-1.54858,1
13,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.62967,-0.15487,1.88511,1.45039,0.12331,0.88113,-0.84637,1
14,-0.95197,0.48246,0.45468,0.96082,-0.31685,1.02119,-0.69509,0.88309,-1.77200,-0.40581,0.19268,0.40148,1
15,1.09449,0.48246,0.45468,0.96082,-0.31685,1.37297,-0.69509,0.29338,1.45039,0.12331,-1.37983,-0.52593,1
16,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,1.13281,-0.43999,0.29338,-0.76096,-0.14277,1.86203,-0.21575,1
17,0.49788,0.48246,1.16365,0.96082,-0.31685,0.62967,-0.15487,-1.97495,-0.15487,-1.01450,0.88113,0.40148,1
18,0.49788,-0.48246,1.98437,-0.28519,-0.31685,1.72012,-0.15487,0.88309,-1.07533,-0.40581,-0.21712,-0.21575,1
19,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-2.05048,0.16767,0.72330,0.13136,0.75830,0.19268,1.22470,1
20,1.09449,-0.48246,1.16365,0.96082,-0.50212,-0.92104,0.80523,-0.31776,0.94156,0.25953,-1.37983,-1.54858,1
21,-0.95197,-0.48246,-1.43719,-0.57009,-0.31685,0.73545,-1.23177,0.58331,-0.60633,-0.40581,0.52975,0.40148,1
22,-0.95197,0.48246,0.45468,0.96082,-0.31685,0.31287,0.16767,-1.55521,0.43852,1.13407,-1.37983,-1.18084,1
23,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.19430,1.74091,1.43533,0.76096,-0.00665,0.88113,1.22470,1
24,-0.07854,0.48246,1.16365,0.96082,-1.10702,-1.32828,0.47617,-0.01928,1.11406,0.12331,-1.37983,-1.54858,1
25,-0.07854,0.48246,1.16365,0.96082,-0.31685,-0.24649,0.80523,-0.58331,1.45039,0.93949,0.19268,-0.84637,1
26,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.58016,0.63779,-1.97495,0.28783,0.75830,-0.71126,-0.52593,1
27,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,2.12700,-0.94779,-0.45174,-0.30172,-1.64101,1.29221,0.07987,1
28,0.49788,-0.48246,0.45468,0.24923,-0.31685,-0.58016,-0.69509,-2.39883,-0.30172,-0.27607,-2.55524,-1.18084,1
29,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.69163,1.28610,1.24033,0.13136,1.13407,0.52975,1.92173,1
30,1.09449,-0.48246,0.45468,0.96082,-0.31685,0.22393,-1.09207,-0.71727,-0.30172,-0.65253,0.19268,-0.84637,1
31,-0.07854,-0.48246,-0.05921,0.96082,-0.31685,-0.05188,-0.94779,-1.68062,0.13136,0.75830,-0.21712,-0.84637,1
32,2.59171,0.48246,-1.73790,0.96082,-0.31685,-0.14882,-0.80615,-0.97631,0.76096,0.41594,-1.37983,-1.54858,1
33,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.14882,0.80523,-1.27553,-0.01729,2.04506,0.19268,-1.18084,1
34,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,1.23461,-1.23177,0.44585,-0.01729,0.25953,-1.37983,-1.54858,1
35,-0.07854,-0.48246,-0.61113,0.96082,-0.31685,0.62967,0.32197,-0.71727,-0.30172,-0.00665,-0.21712,-1.54858,1
36,1.09449,-0.48246,1.16365,0.96082,-0.31685,-0.92104,0.80523,-0.01928,-0.01729,0.41594,-1.37983,-1.54858,1
37,1.09449,0.48246,0.45468,-0.57009,-0.31685,1.23461,1.74091,0.88309,-1.92595,-1.64101,0.88113,1.22470,1
38,0.49788,-0.48246,-0.05921,0.96082,-1.10702,-0.92104,1.45421,-1.27553,-0.45321,-0.00665,-0.21712,0.07987,1
39,0.49788,-0.48246,-0.05921,-0.57009,-0.31685,1.60383,-1.76250,-0.01928,0.13136,-1.51840,0.88113,-0.52593,1
40,-0.07854,-0.48246,0.45468,0.96082,-0.31685,1.23461,-1.76250,-0.31776,0.13136,0.41594,-1.37983,-0.21575,1
41,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.13606,1.11406,-0.97631,0.43852,-0.27607,-0.71126,-0.52593,1
42,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.41667,0.63779,-0.31776,-0.91699,-0.00665,0.19268,0.76540,1
43,-0.07854,0.48246,0.45468,0.96082,-0.50212,-0.24649,2.12700,-2.21069,-0.91699,-0.14277,1.29221,-0.21575,1
44,-0.95197,-0.48246,0.45468,-0.57009,-0.31685,0.62967,1.45421,0.58331,0.13136,0.93949,0.19268,1.92173,1
45,1.09449,0.48246,-1.73790,0.96082,-0.31685,0.41667,-1.37639,-2.09015,0.59042,-0.27607,-1.37983,-2.07848,1
46,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,0.91093,-2.11437,-0.17779,-0.45321,-0.89891,-1.37983,-0.84637,1
47,1.09449,0.48246,0.45468,0.96082,-0.31685,-1.19430,1.58487,0.29338,0.76096,0.41594,-2.55524,-1.18084,1
48,-0.07854,-0.48246,1.16365,0.96082,-0.31685,-0.14882,0.32197,-1.27553,1.11406,1.81175,0.52975,1.22470,1
49,0.49788,0.48246,-0.05921,0.96082,-0.31685,-0.34799,0.80523,-1.68062,-0.60633,0.41594,-0.21712,-0.21575,1

In [52]:
df.describe()

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
count,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.000000,826.0
mean,0.168080,0.085277,0.057608,0.508167,-0.328278,-0.060029,0.027327,-0.197196,0.110081,0.194614,-0.186178,-0.258899,1.0
std,0.909124,0.475151,0.984273,0.659379,0.173798,0.985466,0.978178,0.973696,0.969876,0.972190,0.938166,0.972517,0.0
min,-0.951970,-0.482460,-2.435910,-0.570090,-1.107020,-2.756960,-2.728270,-3.273930,-3.005370,-2.728270,-2.555240,-2.078480,1.0
25%,-0.951970,-0.482460,-0.611130,-0.285190,-0.316850,-0.763195,-0.575450,-0.847320,-0.606330,-0.405810,-0.711260,-0.846370,1.0
50%,-0.078540,0.482460,-0.059210,0.960820,-0.316850,-0.051880,0.003320,-0.177790,0.131360,0.259530,-0.217120,-0.215750,1.0
75%,1.094490,0.482460,0.454680,0.960820,-0.316850,0.629670,0.637790,0.445850,0.760960,0.939490,0.529750,0.401480,1.0
max,2.591710,0.482460,1.984370,0.960820,0.126000,3.273930,2.859500,2.449040,2.756960,3.464360,2.901610,1.921730,1.0

In [53]:
df.isnull().sum()

Age          0
Gender       0
Education    0
Country      0
Ethnicity    0
Nscore       0
Escore       0
Oscore       0
Ascore       0
Cscore       0
Impulsive    0
SS           0
Cannabis     0
dtype: int64

In [54]:
df = df.sample(frac = 1, random_state = 42).reset_index(drop= True)

In [55]:
df.head(50)

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Cannabis
0,-0.07854,0.48246,1.16365,0.96082,-0.22166,0.31287,0.63779,-0.58331,0.13136,-0.14277,0.19268,-0.21575,1
1,-0.95197,-0.48246,-0.61113,-0.57009,0.12600,-0.46725,2.12700,1.88511,-0.60633,-1.25773,1.86203,1.92173,1
2,-0.95197,-0.48246,-0.61113,-0.28519,-0.31685,-1.32828,-0.30033,0.88309,1.11406,-1.01450,-0.71126,-0.21575,1
3,1.09449,0.48246,1.16365,0.96082,-0.31685,-1.05308,1.74091,0.58331,0.43852,2.04506,-0.21712,-0.52593,1
4,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.62967,0.63779,0.44585,0.13136,-2.57309,1.86203,1.22470,1
5,2.59171,-0.48246,0.45468,0.96082,-0.31685,-1.86962,-0.15487,-0.58331,2.46262,0.41594,-1.37983,-2.07848,1
6,-0.95197,-0.48246,-0.05921,0.96082,-0.31685,-0.92104,-0.30033,-0.71727,0.59042,0.41594,-0.71126,-1.54858,1
7,-0.95197,-0.48246,-1.43719,-0.09765,-0.31685,-0.34799,0.80523,0.72330,0.59042,-0.89891,1.86203,1.22470,1
8,1.09449,0.48246,0.45468,0.96082,-0.31685,0.62967,-0.57545,0.72330,-0.15487,0.41594,0.52975,-0.84637,1
9,1.09449,-0.48246,0.45468,0.96082,-0.31685,1.02119,-1.50796,-0.71727,0.28783,-0.89891,-0.21712,0.76540,1
10,1.09449,-0.48246,0.45468,0.96082,-0.31685,1.02119,-0.30033,-0.71727,-0.60633,-0.00665,-1.37983,-1.18084,1
11,-0.95197,-0.48246,-1.73790,-0.09765,-0.31685,0.82562,1.28610,0.29338,-1.21213,-0.89891,0.88113,1.92173,1
12,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,1
13,1.09449,-0.48246,0.45468,0.96082,-0.31685,0.22393,-1.09207,-0.71727,-0.30172,-0.65253,0.19268,-0.84637,1
14,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.31287,-0.57545,-0.31776,-1.47955,-0.89891,-1.37983,0.76540,1
15,-0.95197,0.48246,0.45468,0.96082,-0.31685,-0.58016,0.80523,0.44585,0.59042,1.30612,-0.71126,0.76540,1
16,0.49788,-0.48246,-0.05921,-0.57009,-0.31685,1.60383,-1.76250,-0.01928,0.13136,-1.51840,0.88113,-0.52593,1
17,-0.07854,0.48246,0.45468,-0.57009,0.11440,0.82562,-1.63340,-0.31776,-1.47955,-1.13788,-1.37983,-1.18084,1
18,1.09449,-0.48246,-1.43719,0.96082,-0.31685,0.91093,-0.15487,-0.17779,-0.15487,0.25953,0.88113,0.07987,1
19,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-0.24649,0.16767,-0.31776,-1.21213,0.75830,1.29221,0.40148,1
20,0.49788,0.48246,0.45468,0.96082,-0.31685,-0.67825,0.32197,-0.97631,0.59042,0.12331,-0.71126,-0.84637,1
21,0.49788,0.48246,-1.22751,0.21128,-0.31685,-0.24649,-0.57545,-0.58331,-0.15487,0.25953,-1.37983,-1.54858,1
22,-0.07854,-0.48246,0.45468,-0.09765,-0.31685,1.02119,0.16767,0.58331,0.43852,0.75830,-1.37983,0.76540,1
23,-0.95197,0.48246,0.45468,0.96082,-0.31685,-0.14882,0.96248,-1.55521,2.23427,1.63088,-0.21712,-0.52593,1
24,-0.07854,0.48246,-0.05921,0.96082,-0.31685,-0.67825,0.96248,-1.11902,-0.15487,0.58489,0.19268,-0.21575,1
25,-0.95197,0.48246,1.16365,0.96082,0.12600,0.62967,0.32197,-0.58331,0.13136,0.75830,-0.21712,-0.21575,1
26,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,1.37297,-0.30033,0.29338,-0.15487,-1.78169,0.19268,-0.21575,1
27,1.09449,0.48246,-0.61113,0.96082,-0.31685,0.04257,-0.30033,-2.21069,-0.15487,-0.14277,-0.71126,-0.84637,1
28,-0.07854,-0.48246,-0.05921,0.96082,-0.31685,2.12700,-1.37639,0.14143,-0.30172,-1.64101,1.29221,-0.21575,1
29,1.09449,0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,0.58331,0.13136,0.75830,-2.55524,-0.84637,1
30,-0.07854,-0.48246,-0.61113,-0.57009,-0.31685,0.22393,-1.23177,0.88309,-0.76096,-0.27607,-0.21712,0.76540,1
31,0.49788,0.48246,-0.05921,0.96082,-0.31685,-1.55078,1.45421,0.44585,0.43852,0.58489,-0.71126,-1.18084,1
32,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,1.49158,-1.37639,-2.63199,1.81866,-1.25773,0.52975,-1.18084,1
33,-0.95197,-0.48246,0.45468,-0.57009,-0.31685,0.41667,-1.92173,0.88309,-0.15487,-0.52745,0.19268,-0.52593,1
34,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-0.79151,1.11406,-0.01928,1.28610,2.04506,0.88113,0.40148,1
35,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,0.52135,-0.30033,-0.58331,-0.76096,-0.52745,-0.21712,0.76540,1
36,-0.07854,0.48246,-2.43591,-0.57009,-0.31685,-0.24649,0.63779,-0.71727,-0.91699,0.25953,1.29221,-0.21575,1
37,-0.07854,0.48246,0.45468,0.96082,-0.31685,0.04257,1.28610,-0.01928,0.13136,0.75830,0.52975,0.76540,1
38,1.09449,0.48246,-0.05921,0.96082,-0.31685,-0.58016,0.32197,0.14143,-1.34289,0.93949,0.19268,-0.21575,1
39,2.59171,-0.48246,-0.05921,0.96082,-0.31685,-1.05308,-0.30033,0.29338,0.43852,0.75830,-0.21712,-0.52593,1
40,-0.07854,-0.48246,0.45468,0.96082,-0.31685,-1.19430,1.74091,1.43533,0.76096,-0.00665,0.88113,1.22470,1
41,-0.07854,-0.48246,-0.61113,-0.28519,-0.31685,1.02119,-2.72827,0.14143,-0.01729,-0.14277,0.19268,0.07987,1
42,0.49788,-0.48246,0.45468,-0.28519,-0.31685,1.49158,-0.57545,0.88309,-1.62090,-0.40581,-0.21712,0.76540,1
43,2.59171,0.48246,-1.73790,0.24923,-0.31685,-0.14882,-0.15487,-1.42424,-1.34289,-0.00665,-0.21712,0.76540,1
44,1.09449,-0.48246,-0.05921,0.96082,-0.31685,0.13606,0.00332,-0.45174,-0.60633,0.75830,-0.21712,0.40148,1
45,-0.95197,-0.48246,-0.05921,0.96082,-0.31685,0.91093,-1.37639,-0.31776,-1.92595,-1.38502,0.88113,0.07987,1
46,-0.07854,0.48246,-1.73790,0.96082,-0.31685,-1.19430,-1.23177,-2.21069,1.81866,0.58489,-2.55524,-2.07848,1
47,0.49788,0.48246,1.16365,0.96082,-0.31685,-0.79151,0.32197,-0.01928,-0.15487,1.13407,-0.21712,-0.21575,1
48,-0.07854,0.48246,0.45468,0.96082,-0.31685,-0.14882,-0.30033,-0.84732,-0.30172,1.46191,-0.71126,-0.21575,1
49,-0.95197,-0.48246,-0.61113,0.96082,-0.31685,-0.05188,-2.32338,-0.84732,-1.77200,-0.40581,1.29221,-0.21575,1

In [56]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]

In [57]:
print("X type is " + str(type(X)))
print("X shape is " + str(X.shape))
print("y type is " + str(type(y)))
print("y shape is " + str(y.shape))

X type is <class 'pandas.core.frame.DataFrame'>
X shape is (826, 12)
y type is <class 'pandas.core.series.Series'>
y shape is (826,)

In [58]:
X = X.to_numpy()

In [59]:
y = y.to_numpy().reshape(-1, 1)

In [60]:
print("X type is " + str(type(X)))
print("X shape is " + str(X.shape))
print("y type is " + str(type(y)))
print("y shape is " + str(y.shape))

X type is <class 'numpy.ndarray'>
X shape is (826, 12)
y type is <class 'numpy.ndarray'>
y shape is (826, 1)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
train_df = pd.read_csv('/content/drug_train.csv')
test_df = pd.read_csv('/content/drug_test.csv')

X_train = train_df.drop(columns=['Cannabis']).to_numpy()
y_train = train_df['Cannabis'].to_numpy().reshape(-1, 1)

X_test = test_df.drop(columns=['Cannabis']).to_numpy()
y_test = test_df['Cannabis'].to_numpy().reshape(-1, 1)

In [63]:
import numpy as np

print("Train class distribution:")
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

print("Test class distribution:")
unique, counts = np.unique(y_test, return_counts=True)
print(dict(zip(unique, counts)))

Train class distribution:
{np.int64(0): np.int64(330), np.int64(1): np.int64(330)}
Test class distribution:
{np.int64(0): np.int64(83), np.int64(1): np.int64(83)}

In [64]:
print("X train shape is " + str(X_train.shape))
print("X test shape is " + str(X_test.shape))
print("y train shape is " + str(y_train.shape))
print("y test shape is " + str(y_test.shape))

X train shape is (660, 12)
X test shape is (166, 12)
y train shape is (660, 1)
y test shape is (166, 1)

## Model Mimarisi (Define Network Structure)

Input layer size is X.shape[1]
Hidden layer size is 5.
Output layer size is 1.

Örneğin; giriş katmanı boyutu X.shape[1], gizli katman nöron sayısı 5 ve çıkış katmanı 1 olabilir.

In [65]:
print("X.shape is " + str(X.shape))
print("X.shape[1] is " + str(X.shape[1]))

X.shape is (826, 12)
X.shape[1] is 12

## Modeli Başlatmak (Initialize Model Parameters)

In [66]:
def initialize_parameters(n_x, n_h1, n_h2, n_y=1):
    np.random.seed(42)
    W1 = np.random.randn(n_h1, n_x) * np.sqrt(2. / n_x)
    b1 = np.zeros((n_h1, 1))
    W2 = np.random.randn(n_h2, n_h1) * np.sqrt(2. / n_h1)
    b2 = np.zeros((n_h2, 1))
    W3 = np.random.randn(n_y, n_h2) * np.sqrt(2. / n_h2)
    b3 = np.zeros((n_y, 1))

    parameters = {
        "W1": W1, "b1": b1,
        "W2": W2, "b2": b2,
        "W3": W3, "b3": b3
    }
    return parameters

In [67]:
test_parameters = initialize_parameters(X.shape[1], 5, 1)

In [68]:
print("W1 = " + str(test_parameters["W1"]))
print("b1 = " + str(test_parameters["b1"]))
print("W2 = " + str(test_parameters["W2"]))
print("b2 = " + str(test_parameters["b2"]))
print("W3 = " + str(test_parameters["W3"]))
print("b3 = " + str(test_parameters["b3"]))

W1 = [[ 0.2027827  -0.05644616  0.26441774  0.62177434 -0.09559271 -0.09558601
   0.64471093  0.31330392 -0.19166212  0.22149921 -0.18918948 -0.19013338]
 [ 0.09878068 -0.78109339 -0.70419476 -0.22955292 -0.41348657  0.12829094
  -0.37069928 -0.57657057  0.5983486  -0.09217279  0.02756827 -0.58165101]
 [-0.22224332  0.04528396 -0.46989116  0.15337807 -0.24520972 -0.11908347
  -0.2456457   0.7561894  -0.00551022 -0.43180868  0.33580255 -0.49840733]
 [ 0.08526821 -0.80003198 -0.54222968  0.08036826  0.30147772  0.06996081
  -0.04721321 -0.12292507 -0.60360407 -0.29387517 -0.18805499  0.43156834]
 [ 0.14028158 -0.71975813  0.13230673 -0.15720918 -0.27635225  0.2497158
   0.42090379  0.38019352 -0.34260912 -0.12623542  0.13523773  0.39826463]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.3030564  -0.11742105 -0.69970767 -0.7565475   0.51388645]]
b2 = [[0.]]
W3 = [[1.91801304]]
b3 = [[0.]]

In [69]:
print("W1 = " + str(test_parameters["W1"].shape))
print("b1 = " + str(test_parameters["b1"].shape))
print("W2 = " + str(test_parameters["W2"].shape))
print("b2 = " + str(test_parameters["b2"].shape))
print("W3 = " + str(test_parameters["W3"].shape))
print("b3 = " + str(test_parameters["b3"].shape))
print("X_train = " + str(X_train.shape))

W1 = (5, 12)
b1 = (5, 1)
W2 = (1, 5)
b2 = (1, 1)
W3 = (1, 1)
b3 = (1, 1)
X_train = (660, 12)

## Forward Propagation

In [70]:
def forward_propagation(X, parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    W3 = parameters["W3"]
    b3 = parameters["b3"]

    # gizli katman 1
    Z1 = np.dot(W1, X.T) + b1
    A1 = np.maximum(0, Z1)

    # gizli katman 2
    Z2 = np.dot(W2, A1) + b2
    A2 = np.maximum(0, Z2)

    # çıkış katmanı
    Z3 = np.dot(W3, A2) + b3
    A3 = 1 / (1 + np.exp(-Z3))

    cache = {"Z1": Z1, "A1": A1, "Z2": Z2, "A2": A2, "Z3": Z3, "A3": A3}
    return A3, cache

In [71]:
def sigmoid(Z):
    return 1 / (1 + np.exp(-1 * Z))

In [72]:
test_A3, test_cache = forward_propagation(X_train, test_parameters)

In [73]:
print("A3 test:" + str(test_A3))
print("A3 test shape:" + str(test_A3.shape))

A3 test:[[0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.65261659 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.56148821 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.80007086
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.54118583 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.51533477 0.5        0.5        0.53393552 0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.53444718 0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5103852  0.5        0.5
  0.5        0.5        0.5        0.61778052 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5504087  0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.65505617 0.5        0.60815156 0.5        0.5        0.5
  0.61669344 0.5        0.5        0.80080123 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.60478766
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.55832373 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.50477703 0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.58279785 0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.50388857 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.61907113 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.57429061 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.59204294 0.5        0.5
  0.5        0.5        0.5        0.5        0.53017063 0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.7980078  0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.50236307 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.56252822 0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.62445948 0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.57721321 0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.5        0.5
  0.62178296 0.5        0.5        0.5        0.5        0.5
  0.5        0.5        0.5        0.5        0.61315776 0.56569426
  0.5        0.5        0.5        0.5        0.6773829  0.5
  0.5        0.5        0.5        0.5        0.5        0.5       ]]
A3 test shape:(1, 660)

In [74]:
print("Z1 is:" + str(test_cache["Z1"]))
print("A1 is:" + str(test_cache["A1"]))
print("Z2 is:" + str(test_cache["Z2"]))
print("A2 is:" + str(test_cache["A2"]))
print("Z3 is:" + str(test_cache["Z3"]))
print("A3 is:" + str(test_cache["A3"]))

Z1 is:[[ 0.2642465  -1.55293961  1.1323356  ...  1.24818692 -0.38530402
   0.09411224]
 [ 1.29259898  2.69170413  0.54295221 ... -1.84143817  1.21832267
  -0.32551391]
 [-0.17951881  1.10027563 -1.42351879 ...  0.97769385 -0.36940204
  -0.01148575]
 [ 0.10651001  1.88306948 -1.12002022 ...  2.26294772  0.8834147
  -1.21474675]
 [ 0.35134741  0.0738283  -1.49366595 ...  1.63754344 -0.88126435
  -0.77040529]]
A1 is:[[0.2642465  0.         1.1323356  ... 1.24818692 0.         0.09411224]
 [1.29259898 2.69170413 0.54295221 ... 0.         1.21832267 0.        ]
 [0.         1.10027563 0.         ... 0.97769385 0.         0.        ]
 [0.10651001 1.88306948 0.         ... 2.26294772 0.8834147  0.        ]
 [0.35134741 0.0738283  0.         ... 1.63754344 0.         0.        ]]
Z2 is:[[-0.13188713 -2.47262616 -0.40691557 -0.3655988  -2.73762526 -1.62469887
  -2.3561837  -0.90941508 -0.27595157 -2.35647408 -0.73189468 -0.62034891
  -0.24448745 -0.61665544 -1.84819625 -0.07403413 -0.86819669 -0.54811161
  -0.46551694 -0.73207146 -1.13677422 -1.08317458 -0.32558293 -1.56341417
  -0.19542323 -1.26770618 -0.14401021 -0.54247053 -1.24468813 -0.66421342
  -0.57614176 -0.69349509 -0.62744211  0.32875725 -0.60320114 -0.26132644
  -0.43234308 -0.41975214  0.         -0.55155606 -0.13474885 -0.36133483
  -0.5318381  -0.65476679 -0.07497754 -0.22671599 -0.55610388 -0.6040415
  -0.12001458 -0.17108706 -0.30794301 -0.72171614 -0.93373956 -0.34937251
  -0.15580508 -0.31173604 -1.91250185 -0.1264691  -1.96690113 -0.3998554
  -0.20817913 -1.46877848 -0.32349722 -0.0894236  -1.72914731 -1.29510955
  -0.56446835 -0.62989933 -0.26443382 -0.51915845 -0.27315881 -0.37646999
  -0.40581488 -0.34489264 -0.05688333 -0.48721793 -0.39106571 -0.29336623
  -0.41918988 -0.21575839 -1.47313139 -0.69566915 -0.69757655 -0.80787846
  -0.95120044 -0.13585739 -2.18906734 -0.28441313 -0.04231809 -0.62600299
  -0.39603019 -1.9081284  -0.32232124 -0.64205296 -0.74881174 -1.22298027
  -0.25208933 -0.07067658  0.12888551 -0.46796197 -0.92962051 -0.59552647
  -0.71834052 -1.16982097 -0.38173125 -0.90254803 -0.33650772 -1.68926181
  -1.58098422 -0.065895   -0.77488334 -0.52772479 -0.21566436  0.72300722
  -0.36965939 -0.42717364 -0.54096233 -0.67358869 -0.14174033 -0.99369187
  -0.49873886 -0.29885608 -0.224817   -0.8135359  -0.48433957 -0.60564595
  -1.38506287 -0.7505942   0.08608776 -0.41017861 -0.45897559 -0.6895297
  -0.71229715 -1.23020391 -2.16059504 -0.05954753 -0.52552821 -0.09574065
  -1.10034648 -0.31330497 -0.73940773 -0.24763419 -0.93525235 -0.20491329
  -0.73083607 -0.33225868 -0.71747354 -1.05153491 -0.57676473 -0.31113549
  -0.57916604  0.03199058 -0.8557688  -0.27032544  0.07088121 -0.72688636
  -0.36638781 -0.36169476 -0.55000274 -0.66432051 -1.59418686 -0.20971967
  -0.31646593 -1.45939053 -1.27905138 -0.49248997 -0.48059358 -0.41260195
  -2.06827538 -0.30566809 -0.8132138  -0.33854699  0.07195329 -0.32589158
  -1.29995892 -1.84042995 -0.22906026 -0.46296191 -0.51198861 -0.95058735
  -1.38667457 -1.66955612 -0.41812444  0.02166135 -0.58796233 -0.42552798
  -0.2610482  -0.04413264 -0.60262034  0.25033107 -1.08255097 -0.41129806
  -0.57109321 -0.5428848  -0.56430406 -0.55290029  0.         -0.50873423
  -0.61328715 -0.64383603  0.10548528 -0.39512516 -0.2341514  -0.25900893
  -0.30385896 -1.08841935 -0.30028445 -1.55975758 -0.56901198 -0.65470485
  -1.8997886  -0.18341684 -1.30427907 -0.03908904 -1.26136792 -0.99159852
   0.33437696 -0.7729348   0.22916893 -0.49710336 -0.3277696  -0.60239686
   0.24793207 -0.50600375 -0.38753107  0.7253911  -1.87887583 -1.33471556
  -1.64845102 -0.59215408 -2.27772116 -0.38349696 -0.67338663 -0.90122579
  -0.23222114 -1.60538033 -0.84192012 -1.75635791 -0.35986303 -0.81534637
  -1.74007337 -0.99291675 -0.79623485 -1.20643291 -0.7396887  -0.47425825
  -0.34929082 -0.96785434 -0.53190502 -1.32053619 -2.52000202 -0.02904548
  -0.84348192 -0.99808223 -0.70928729 -0.38670125 -0.66289099 -0.72115302
  -1.33910813 -0.40509592 -0.53201006 -0.31152267 -0.386256    0.2218203
  -0.73631412 -0.31574543 -0.62636794 -0.99147376 -0.23282429 -1.24529497
  -0.53692853 -0.50139248  0.12218987 -0.38404666 -0.36701004 -0.52196694
  -0.38462899 -0.71396881 -0.87434515 -0.61009124 -0.92308069 -0.24883981
  -0.49429448 -1.60261122 -1.38506957 -0.31458464 -0.22173382 -0.48761424
  -0.34876775 -1.82220098 -0.40017439 -0.46953477 -2.1507524  -2.42712894
  -0.47950241 -0.52473513 -1.09783421 -0.22970366 -0.02676427 -0.79645104
  -1.14604439 -0.69103839 -0.39602253 -0.83010641 -0.26800469 -0.22420504
  -1.69721025  0.00996276 -0.44998608 -0.33682113 -0.39665771 -0.16689269
  -1.69719366 -0.2790288  -1.28165901 -0.44808347 -0.30064808 -0.42540655
  -0.24755301 -1.14929948 -1.02036215 -0.98034416 -0.24477133 -0.48204275
  -0.67808697  0.17427906 -0.8395568  -0.49982809 -0.46163562 -0.51811042
  -0.3880423  -0.50087759 -0.49040187 -0.00341077 -1.7560477  -0.22664292
  -0.25482849 -0.02918453 -0.55644711 -1.58870478 -0.44122628 -0.5935176
  -0.1001433  -0.44223325 -0.78720203 -0.76842875 -1.56286675 -0.13439873
  -0.63576284 -1.02283278 -1.41239607 -0.51767412 -2.48175133 -1.29102288
  -0.52845049 -0.67973871 -0.23491607 -0.53177743 -0.38853308 -0.18897709
  -0.09585632 -0.36574483 -0.89626745 -0.74495298 -0.22437738  0.
  -0.43184074 -0.69148857 -1.00418219 -0.67644542 -0.67765865 -0.31626251
  -0.54016107 -0.82107221 -1.60942884 -0.2875839  -0.79603068 -0.52832318
  -0.98874531 -0.61624331 -0.18624429 -1.80019668 -0.0741717  -0.28616327
  -0.51053877 -0.14067214  0.00810975 -0.44346672 -0.3535173  -0.57008562
  -0.29282651 -1.45911088 -0.29099371 -0.61337811 -0.41276644 -0.36040908
  -1.85080288 -0.27495568 -0.82084243 -0.59358869 -0.58900263 -0.30238765
  -0.73607848 -1.34018892 -0.12159389  0.2531826  -0.79587679 -0.59208862
  -0.85462495 -0.23639149 -0.60021646 -0.68344178 -0.55567952 -0.13648004
  -0.42289391 -0.83124936 -0.63650759 -0.39862897 -0.240268   -0.93708803
  -0.03104664 -1.74282147 -0.01736811  0.15608791 -0.48054775 -0.2749372
  -0.75538091 -0.15990732 -0.53941112 -0.94519321 -1.74500234 -2.17863222
  -0.43978442 -2.08909021 -0.87975007 -0.61980104 -1.56138497 -0.19140707
  -0.81078966 -0.23268999 -0.26651956 -2.95721479 -0.44601676 -0.02171186
  -0.75429187 -0.5863577  -0.92401041  0.19416825 -1.02980451 -0.2178217
  -0.51291196 -0.36368767 -0.3961176  -0.28660459  0.06299712 -1.40363696
  -0.06795572 -0.40734873 -0.58528993 -0.19167802 -0.46310712 -0.4411764
  -0.45301144 -0.26086178 -0.42053694 -0.53067938 -0.57841355 -0.40473629
  -0.4522093  -0.73074774 -0.40244361 -0.14425295 -0.57207849 -2.44323553
  -0.95187956 -0.83482412 -0.42533242 -0.4264342  -0.93249754 -1.1046951
  -1.86418835 -0.37657748 -0.27704929 -0.08679491 -2.76505731 -0.51347642
   0.71630862 -1.49086452 -1.26541578 -0.76457652 -0.51896374 -0.74696909
  -0.30931867 -0.63381444  0.00492821 -0.95077309 -0.88028734 -0.53601891
  -0.51697869 -0.35935368 -0.51716234 -2.18486816 -0.5601825  -0.83506581
  -2.85250711 -1.51331832 -0.72012558 -0.57173277 -1.42007903 -0.31197577
  -0.25098424 -0.72988629 -2.35206985 -1.81254244 -0.32082121 -0.39848968
  -0.90567439 -1.36699609 -0.31462635 -0.43057198 -0.84167218 -0.59299759
  -0.58907707 -1.21248051 -2.12884462 -0.49397175 -0.74570862 -0.35414939
  -0.32073381 -0.27852137 -0.12071854 -1.49896558 -0.21330009 -0.28901715
  -1.83600517 -0.03332687 -0.80446862 -0.34989547 -0.65057818 -0.37523536
  -0.31526547 -0.82314051 -0.52501819 -0.18609764 -0.33863601 -0.23796334
  -0.69101478 -0.63667708 -0.32016751 -1.12419292 -0.33992685 -0.19005956
  -0.37285039 -0.46549376 -0.56692522 -0.06845783 -0.36043149 -1.20577478
  -0.53911581 -0.40328633 -1.4249006  -0.34876353 -1.48204142 -1.29645151
  -0.71546807 -0.50374996 -0.66466091 -1.28165004 -0.47349942 -0.33964845
  -3.15399072 -0.00793269 -0.0520434  -0.73843844 -0.75941356 -0.50577679
  -0.88778661 -1.4562044  -0.81161426 -0.48055033 -0.2312798  -2.15953503
  -1.19934225 -0.07308862  0.13108832 -0.35278841 -0.01524949 -0.28041008
  -0.7557734  -0.6292809  -0.76197507 -1.99719408 -0.29457572 -0.89767158
  -0.049488   -0.38686042 -0.32559381  0.26512858 -0.49011566 -1.70002501
  -1.38946079 -1.73861552 -0.46163738 -0.30727836 -0.27561733 -0.73051436
  -1.46445526 -0.51264858 -0.14288295 -0.21204244 -1.50121505 -0.40330826
  -1.10528704 -1.30554266 -0.5728691  -0.30854629 -0.31160591 -0.48122601
  -0.62553664 -0.45054306 -0.51252066 -0.08953542 -0.42177164 -0.12646795
   0.16232618 -1.25742058 -0.37527487 -0.39875204 -0.88606845 -0.5072568
  -0.28581279 -0.38626618 -0.40575643 -2.61523403 -1.09174205 -0.88670714
   0.2591864  -0.233101   -0.57586918 -0.61205526 -0.91831258 -0.60249195
  -1.13727783 -0.96854291 -0.21540092 -1.33490441  0.24014712  0.13780146
  -0.7959384  -1.05329566 -0.61786622 -0.55253369  0.38673904 -0.31737858
  -0.99692771 -0.17662751 -0.46288567 -1.93288697 -0.8114019  -0.02852132]]
A2 is:[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.32875725 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.12888551 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.72300722
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.08608776 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.03199058 0.         0.         0.07088121 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.07195329 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.02166135 0.         0.
  0.         0.         0.         0.25033107 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.10548528 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.33437696 0.         0.22916893 0.         0.         0.
  0.24793207 0.         0.         0.7253911  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.2218203
  0.         0.         0.         0.         0.         0.
  0.         0.         0.12218987 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.00996276 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.17427906 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.00810975 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.2531826  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.15608791 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.19416825 0.         0.
  0.         0.         0.         0.         0.06299712 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.71630862 0.         0.         0.         0.         0.
  0.         0.         0.00492821 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.13108832 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.26512858 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.16232618 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.2591864  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.24014712 0.13780146
  0.         0.         0.         0.         0.38673904 0.
  0.         0.         0.         0.         0.         0.        ]]
Z3 is:[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.63056069 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.24720409 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.38673727
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.16511745 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.06135834 0.         0.         0.13595108 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.13800735 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.04154676 0.         0.
  0.         0.         0.         0.48013827 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.20232214 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.64133937 0.         0.439549   0.         0.         0.
  0.47553695 0.         0.         1.3913096  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.42545424
  0.         0.         0.         0.         0.         0.
  0.         0.         0.23436176 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.01910871 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.3342695  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.0155546  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.48560753 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.29937865 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.

## Compute Cost

In [75]:
print("Y shape is " +str(y_train.shape))

Y shape is (660, 1)

In [76]:
def compute_cost(A3, Y):
    m = A3.shape[1]
    cost = - (np.dot(np.log(A3), Y) + np.dot(np.log(1 - A3), (1 - Y))) / m
    cost = float(np.squeeze(cost))
    return cost

In [77]:
test_cost = compute_cost(test_A3, y_train)

In [78]:
print("test_cost is " + str(test_cost))
print("test_cost type is " + str(type(test_cost)))

test_cost is 0.6900340344955644
test_cost type is <class 'float'>

## Backpropagation

In [79]:
print("A1 shape: " + str(test_cache["A1"].shape))
print("A2 shape: " + str(test_cache["A2"].shape))
print("A3 shape: " + str(test_cache["A3"].shape))
print("W1 shape: " + str(test_parameters["W1"].shape))
print("W2 shape: " + str(test_parameters["W2"].shape))
print("W3 shape: " + str(test_parameters["W3"].shape))
print("y train shape: " + str(y_train.shape))
print("X_train shape: " + str(X_train.shape))

A1 shape: (5, 660)
A2 shape: (1, 660)
A3 shape: (1, 660)
W1 shape: (5, 12)
W2 shape: (1, 5)
W3 shape: (1, 1)
y train shape: (660, 1)
X_train shape: (660, 12)

In [80]:
def backpropagation(X, Y, cache, parameters):
    m = X.shape[0]

    W2 = parameters["W2"]
    W3 = parameters["W3"]
    A1 = cache["A1"]
    A2 = cache["A2"]
    A3 = cache["A3"]

    # çıkış katmanı gradyanları
    dZ3 = A3 - Y.T
    dW3 = np.dot(dZ3, A2.T) / m
    db3 = np.sum(dZ3, axis=1, keepdims=True) / m

    # gizli katman 2 gradyanları
    dZ2 = np.dot(W3.T, dZ3) * np.where(A2 > 0, 1, 0)
    dW2 = np.dot(dZ2, A1.T) / m
    db2 = np.sum(dZ2, axis=1, keepdims=True) / m

    # gizli katman 1 gradyanları
    dZ1 = np.dot(W2.T, dZ2) * np.where(A1 > 0, 1, 0)
    dW1 = np.dot(dZ1, X) / m
    db1 = np.sum(dZ1, axis=1, keepdims=True) / m

    grads = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2, "dW3": dW3, "db3": db3}
    return grads

In [81]:
test_grads = backpropagation(X_train, y_train, test_cache, test_parameters)

In [82]:
print("dW1 shape is: " + str(test_grads["dW1"].shape))
print("dW2 shape is: " + str(test_grads["dW2"].shape))
print("dW3 shape is: " + str(test_grads["dW3"].shape))
print("db1 shape is: " + str(test_grads["db1"].shape))
print("db2 shape is: " + str(test_grads["db2"].shape))
print("db3 shape is: " + str(test_grads["db3"].shape))
print("b1 shape is: " + str(test_parameters["b1"].shape))

dW1 shape is: (5, 12)
dW2 shape is: (1, 5)
dW3 shape is: (1, 1)
db1 shape is: (5, 1)
db2 shape is: (1, 1)
db3 shape is: (1, 1)
b1 shape is: (5, 1)

In [83]:
def update_parameters(parameters, grads, learning_rate=0.05):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    W3 = parameters["W3"]
    b3 = parameters["b3"]

    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]
    dW3 = grads["dW3"]
    db3 = grads["db3"]

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W3 -= learning_rate * dW3
    b3 -= learning_rate * db3

    parameters = {
        "W1": W1, "b1": b1,
        "W2": W2, "b2": b2,
        "W3": W3, "b3": b3
    }

    return parameters

In [84]:
test_learned_parameters = update_parameters(test_parameters, test_grads)

In [85]:
test_learned_parameters["b3"].shape

(1, 1)

In [86]:
def nn_model(X, Y, n_x, n_h1, n_h2, n_y, n_steps=100, print_cost=True):
    parameters = initialize_parameters(n_x, n_h1, n_h2, n_y)

    for i in range(0, n_steps):
        A3, cache = forward_propagation(X, parameters)
        cost = compute_cost(A3, Y)
        grads = backpropagation(X, Y, cache, parameters)
        parameters = update_parameters(parameters, grads)

        if print_cost and i % 10 == 0:
            print("cost %i %f" %(i, cost))

    return parameters

In [87]:
X_train.shape

(660, 12)

In [88]:
parameters = nn_model(X_train, y_train, X_train.shape[1], n_h1=3, n_h2=3, n_y=1, n_steps=500)

cost 0 0.688567
cost 10 0.684308
cost 20 0.680855
cost 30 0.677784
cost 40 0.674801
cost 50 0.671950
cost 60 0.669028
cost 70 0.665974
cost 80 0.662928
cost 90 0.659882
cost 100 0.656571
cost 110 0.653160
cost 120 0.649651
cost 130 0.645987
cost 140 0.642235
cost 150 0.638409
cost 160 0.634491
cost 170 0.630601
cost 180 0.626602
cost 190 0.622604
cost 200 0.618600
cost 210 0.614591
cost 220 0.610602
cost 230 0.606644
cost 240 0.602696
cost 250 0.598716
cost 260 0.594788
cost 270 0.590861
cost 280 0.587250
cost 290 0.583816
cost 300 0.580456
cost 310 0.577294
cost 320 0.574289
cost 330 0.571525
cost 340 0.568942
cost 350 0.566466
cost 360 0.564047
cost 370 0.561693
cost 380 0.559389
cost 390 0.557156
cost 400 0.554993
cost 410 0.552915
cost 420 0.550910
cost 430 0.549028
cost 440 0.547262
cost 450 0.545503
cost 460 0.543775
cost 470 0.542145
cost 480 0.540589
cost 490 0.539075

In [89]:
def predict(parameters, X):
    A3, cache = forward_propagation(X, parameters)
    predicts = A3 > 0.5
    return predicts

In [90]:
predicts = predict(parameters, X_test)

In [91]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
y_true = y_test.flatten()
y_pred = predicts.flatten()
acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='binary')
recall = recall_score(y_true, y_pred, average='binary')
f1 = f1_score(y_true, y_pred, average='binary')
conf_matrix = confusion_matrix(y_true, y_pred)
print(f"Accuracy: {acc:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_report(y_true, y_pred))

Accuracy: 0.8313
Precision: 0.8481
Recall: 0.8072
F1 Score: 0.8272

Confusion Matrix:
[[71 12]
 [16 67]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84        83
           1       0.85      0.81      0.83        83

    accuracy                           0.83       166
   macro avg       0.83      0.83      0.83       166
weighted avg       0.83      0.83      0.83       166

In [92]:
parameters_n_h = [i for i in range(3, 11)]
parameters_n_steps = [i for i in range(100, 1100, 100)]

for n_h in parameters_n_h:
    for n_step in parameters_n_steps:
        parameters = nn_model(X_train, y_train, X_train.shape[1], n_h1=n_h, n_h2=n_h, n_y=1, n_steps=n_step, print_cost=False)
        predicts = predict(parameters, X_test)
        acc = accuracy_score(y_test.flatten(), predicts.flatten())
        print(f"n_h1: {n_h}, n_h2: {n_h}, n_step: {n_step}, acc: {acc}")

n_h1: 3, n_h2: 3, n_step: 100, acc: 0.7530120481927711
n_h1: 3, n_h2: 3, n_step: 200, acc: 0.7771084337349398
n_h1: 3, n_h2: 3, n_step: 300, acc: 0.8373493975903614
n_h1: 3, n_h2: 3, n_step: 400, acc: 0.8373493975903614
n_h1: 3, n_h2: 3, n_step: 500, acc: 0.8313253012048193
n_h1: 3, n_h2: 3, n_step: 600, acc: 0.8313253012048193
n_h1: 3, n_h2: 3, n_step: 700, acc: 0.8373493975903614
n_h1: 3, n_h2: 3, n_step: 800, acc: 0.8313253012048193
n_h1: 3, n_h2: 3, n_step: 900, acc: 0.8313253012048193
n_h1: 3, n_h2: 3, n_step: 1000, acc: 0.8313253012048193
n_h1: 4, n_h2: 4, n_step: 100, acc: 0.7650602409638554
n_h1: 4, n_h2: 4, n_step: 200, acc: 0.8012048192771084
n_h1: 4, n_h2: 4, n_step: 300, acc: 0.8192771084337349
n_h1: 4, n_h2: 4, n_step: 400, acc: 0.8132530120481928
n_h1: 4, n_h2: 4, n_step: 500, acc: 0.7951807228915663
n_h1: 4, n_h2: 4, n_step: 600, acc: 0.7951807228915663
n_h1: 4, n_h2: 4, n_step: 700, acc: 0.7951807228915663
n_h1: 4, n_h2: 4, n_step: 800, acc: 0.8132530120481928
n_h1: 4, n_h2: 4, n_step: 900, acc: 0.8132530120481928
n_h1: 4, n_h2: 4, n_step: 1000, acc: 0.8253012048192772
n_h1: 5, n_h2: 5, n_step: 100, acc: 0.7891566265060241
n_h1: 5, n_h2: 5, n_step: 200, acc: 0.8253012048192772
n_h1: 5, n_h2: 5, n_step: 300, acc: 0.8313253012048193
n_h1: 5, n_h2: 5, n_step: 400, acc: 0.8313253012048193
n_h1: 5, n_h2: 5, n_step: 500, acc: 0.8253012048192772
n_h1: 5, n_h2: 5, n_step: 600, acc: 0.8192771084337349
n_h1: 5, n_h2: 5, n_step: 700, acc: 0.8313253012048193
n_h1: 5, n_h2: 5, n_step: 800, acc: 0.8192771084337349
n_h1: 5, n_h2: 5, n_step: 900, acc: 0.8192771084337349
n_h1: 5, n_h2: 5, n_step: 1000, acc: 0.8192771084337349
n_h1: 6, n_h2: 6, n_step: 100, acc: 0.7771084337349398
n_h1: 6, n_h2: 6, n_step: 200, acc: 0.8192771084337349
n_h1: 6, n_h2: 6, n_step: 300, acc: 0.8313253012048193
n_h1: 6, n_h2: 6, n_step: 400, acc: 0.8313253012048193
n_h1: 6, n_h2: 6, n_step: 500, acc: 0.8373493975903614
n_h1: 6, n_h2: 6, n_step: 600, acc: 0.8493975903614458
n_h1: 6, n_h2: 6, n_step: 700, acc: 0.8433734939759037
n_h1: 6, n_h2: 6, n_step: 800, acc: 0.8433734939759037
n_h1: 6, n_h2: 6, n_step: 900, acc: 0.8433734939759037
n_h1: 6, n_h2: 6, n_step: 1000, acc: 0.8433734939759037
n_h1: 7, n_h2: 7, n_step: 100, acc: 0.8012048192771084
n_h1: 7, n_h2: 7, n_step: 200, acc: 0.8373493975903614
n_h1: 7, n_h2: 7, n_step: 300, acc: 0.8373493975903614
n_h1: 7, n_h2: 7, n_step: 400, acc: 0.8433734939759037
n_h1: 7, n_h2: 7, n_step: 500, acc: 0.8433734939759037
n_h1: 7, n_h2: 7, n_step: 600, acc: 0.8313253012048193
n_h1: 7, n_h2: 7, n_step: 700, acc: 0.8313253012048193
n_h1: 7, n_h2: 7, n_step: 800, acc: 0.8253012048192772
n_h1: 7, n_h2: 7, n_step: 900, acc: 0.8253012048192772
n_h1: 7, n_h2: 7, n_step: 1000, acc: 0.8132530120481928
n_h1: 8, n_h2: 8, n_step: 100, acc: 0.7831325301204819
n_h1: 8, n_h2: 8, n_step: 200, acc: 0.8072289156626506
n_h1: 8, n_h2: 8, n_step: 300, acc: 0.8132530120481928
n_h1: 8, n_h2: 8, n_step: 400, acc: 0.8253012048192772
n_h1: 8, n_h2: 8, n_step: 500, acc: 0.8373493975903614
n_h1: 8, n_h2: 8, n_step: 600, acc: 0.8253012048192772
n_h1: 8, n_h2: 8, n_step: 700, acc: 0.8313253012048193
n_h1: 8, n_h2: 8, n_step: 800, acc: 0.8373493975903614
n_h1: 8, n_h2: 8, n_step: 900, acc: 0.8373493975903614
n_h1: 8, n_h2: 8, n_step: 1000, acc: 0.8373493975903614
n_h1: 9, n_h2: 9, n_step: 100, acc: 0.8012048192771084
n_h1: 9, n_h2: 9, n_step: 200, acc: 0.8012048192771084
n_h1: 9, n_h2: 9, n_step: 300, acc: 0.8072289156626506
n_h1: 9, n_h2: 9, n_step: 400, acc: 0.8072289156626506
n_h1: 9, n_h2: 9, n_step: 500, acc: 0.8072289156626506
n_h1: 9, n_h2: 9, n_step: 600, acc: 0.8072289156626506
n_h1: 9, n_h2: 9, n_step: 700, acc: 0.8132530120481928
n_h1: 9, n_h2: 9, n_step: 800, acc: 0.8132530120481928
n_h1: 9, n_h2: 9, n_step: 900, acc: 0.7951807228915663
n_h1: 9, n_h2: 9, n_step: 1000, acc: 0.7951807228915663
n_h1: 10, n_h2: 10, n_step: 100, acc: 0.7710843373493976
n_h1: 10, n_h2: 10, n_step: 200, acc: 0.8012048192771084
n_h1: 10, n_h2: 10, n_step: 300, acc: 0.8132530120481928
n_h1: 10, n_h2: 10, n_step: 400, acc: 0.8132530120481928
n_h1: 10, n_h2: 10, n_step: 500, acc: 0.8253012048192772
n_h1: 10, n_h2: 10, n_step: 600, acc: 0.8373493975903614
n_h1: 10, n_h2: 10, n_step: 700, acc: 0.8373493975903614
n_h1: 10, n_h2: 10, n_step: 800, acc: 0.8253012048192772
n_h1: 10, n_h2: 10, n_step: 900, acc: 0.8253012048192772
n_h1: 10, n_h2: 10, n_step: 1000, acc: 0.8192771084337349